{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "a=pd.Series(np.arange(2,9))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0    2\n",
       "1    3\n",
       "2    4\n",
       "3    5\n",
       "4    6\n",
       "5    7\n",
       "6    8\n",
       "dtype: int32"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "a"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "b=pd.Series(np.arange(2,9), index=['z','y','x','w','v','u','n'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "z    2\n",
       "y    3\n",
       "x    4\n",
       "w    5\n",
       "v    6\n",
       "u    7\n",
       "n    8\n",
       "dtype: int32"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "b"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "url = 'https://api.github.com/repos/pandas-dev/pandas/issues'\n",
    "r = requests.get(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<Response [200]>"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "r"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "u=r.json()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39925',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39925/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39925/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39925/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/pull/39925',\n",
       "  'id': 812513512,\n",
       "  'node_id': 'MDExOlB1bGxSZXF1ZXN0NTc2ODY1NzM4',\n",
       "  'number': 39925,\n",
       "  'title': 'Updated read_html to add option',\n",
       "  'user': {'login': 'Derekt2',\n",
       "   'id': 28223951,\n",
       "   'node_id': 'MDQ6VXNlcjI4MjIzOTUx',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/28223951?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/Derekt2',\n",
       "   'html_url': 'https://github.com/Derekt2',\n",
       "   'followers_url': 'https://api.github.com/users/Derekt2/followers',\n",
       "   'following_url': 'https://api.github.com/users/Derekt2/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/Derekt2/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/Derekt2/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/Derekt2/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/Derekt2/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/Derekt2/repos',\n",
       "   'events_url': 'https://api.github.com/users/Derekt2/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/Derekt2/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': None,\n",
       "  'comments': 1,\n",
       "  'created_at': '2021-02-20T04:41:01Z',\n",
       "  'updated_at': '2021-02-20T04:41:06Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'NONE',\n",
       "  'active_lock_reason': None,\n",
       "  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/39925',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/pull/39925',\n",
       "   'diff_url': 'https://github.com/pandas-dev/pandas/pull/39925.diff',\n",
       "   'patch_url': 'https://github.com/pandas-dev/pandas/pull/39925.patch'},\n",
       "  'body': 'Adds optional boolean parameter \"remove_whitespace\" to skip the remove_whitespace functionality. Defaults to true to support backwards compatibility. See https://github.com/pandas-dev/pandas/issues/24766\\r\\n\\r\\n- [ x ] closes #24766 \\r\\n- [ ] tests added / passed\\r\\n- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them\\r\\n- [ ] whatsnew entry\\r\\n',\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39924',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39924/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39924/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39924/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/39924',\n",
       "  'id': 812509085,\n",
       "  'node_id': 'MDU6SXNzdWU4MTI1MDkwODU=',\n",
       "  'number': 39924,\n",
       "  'title': 'Assinging a row using `DateFrame.loc` sometimes fails to preserve type of data',\n",
       "  'user': {'login': 'probaddie',\n",
       "   'id': 12599243,\n",
       "   'node_id': 'MDQ6VXNlcjEyNTk5MjQz',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/12599243?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/probaddie',\n",
       "   'html_url': 'https://github.com/probaddie',\n",
       "   'followers_url': 'https://api.github.com/users/probaddie/followers',\n",
       "   'following_url': 'https://api.github.com/users/probaddie/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/probaddie/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/probaddie/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/probaddie/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/probaddie/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/probaddie/repos',\n",
       "   'events_url': 'https://api.github.com/users/probaddie/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/probaddie/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': None,\n",
       "  'comments': 0,\n",
       "  'created_at': '2021-02-20T04:11:15Z',\n",
       "  'updated_at': '2021-02-20T04:11:15Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'NONE',\n",
       "  'active_lock_reason': None,\n",
       "  'body': \"When assigning a singleton row to a DataFrame with integer type using an `Index` and column, the stored row's `dtype` is sometimes converted to `float64`.\\r\\n\\r\\nMinimum reproducing example:\\r\\n\\r\\n```\\r\\nimport pandas as pd\\r\\nimport numpy as np\\r\\n\\r\\nprint(pd.__version__)\\r\\nprint()\\r\\n\\r\\ndf1 = pd.DataFrame({'bar': [0, 1]})  # Initializing with at least one row seems necessary to reproduce\\r\\ndf1.loc[df1.index[:], 'foo'] = np.array([0, 1], dtype=np.int16)\\r\\nprint(df1['foo'])\\r\\nprint()\\r\\n\\r\\ndf2 = pd.DataFrame({'bar': [0]})\\r\\ndf2.loc[df2.index[:], 'foo'] = np.array([0], dtype=np.int16)\\r\\nprint(df2['foo'])\\r\\nprint()\\r\\n```\\r\\n\\r\\nOutput:\\r\\n```\\r\\n1.2.2\\r\\n\\r\\n0    0\\r\\n1    1\\r\\nName: foo, dtype: int16\\r\\n\\r\\n0    0.0\\r\\nName: foo, dtype: float64\\r\\n```\\r\\n\",\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39923',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39923/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39923/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39923/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/pull/39923',\n",
       "  'id': 812502813,\n",
       "  'node_id': 'MDExOlB1bGxSZXF1ZXN0NTc2ODU3NDg2',\n",
       "  'number': 39923,\n",
       "  'title': 'REF: De-duplicate ExtensionIndex._validate_fill_value',\n",
       "  'user': {'login': 'jbrockmendel',\n",
       "   'id': 8078968,\n",
       "   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/jbrockmendel',\n",
       "   'html_url': 'https://github.com/jbrockmendel',\n",
       "   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',\n",
       "   'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/jbrockmendel/repos',\n",
       "   'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': None,\n",
       "  'comments': 0,\n",
       "  'created_at': '2021-02-20T03:35:00Z',\n",
       "  'updated_at': '2021-02-20T03:35:00Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'MEMBER',\n",
       "  'active_lock_reason': None,\n",
       "  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/39923',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/pull/39923',\n",
       "   'diff_url': 'https://github.com/pandas-dev/pandas/pull/39923.diff',\n",
       "   'patch_url': 'https://github.com/pandas-dev/pandas/pull/39923.patch'},\n",
       "  'body': '- [ ] closes #xxxx\\r\\n- [ ] tests added / passed\\r\\n- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them\\r\\n- [ ] whatsnew entry\\r\\n',\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39922',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39922/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39922/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39922/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/pull/39922',\n",
       "  'id': 812446043,\n",
       "  'node_id': 'MDExOlB1bGxSZXF1ZXN0NTc2ODEwNTg2',\n",
       "  'number': 39922,\n",
       "  'title': 'BENCH: collect isin asvs',\n",
       "  'user': {'login': 'jbrockmendel',\n",
       "   'id': 8078968,\n",
       "   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/jbrockmendel',\n",
       "   'html_url': 'https://github.com/jbrockmendel',\n",
       "   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',\n",
       "   'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/jbrockmendel/repos',\n",
       "   'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': None,\n",
       "  'comments': 0,\n",
       "  'created_at': '2021-02-20T00:15:21Z',\n",
       "  'updated_at': '2021-02-20T02:05:18Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'MEMBER',\n",
       "  'active_lock_reason': None,\n",
       "  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/39922',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/pull/39922',\n",
       "   'diff_url': 'https://github.com/pandas-dev/pandas/pull/39922.diff',\n",
       "   'patch_url': 'https://github.com/pandas-dev/pandas/pull/39922.patch'},\n",
       "  'body': 'Pushes these as far towards parametrization as I can get them.  We end up adding a few cases, dropping none.\\r\\n\\r\\nDecides on a policy to benchmark Series.isin and leave the others alone (see `algos/__init__.py`)',\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39921',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39921/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39921/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39921/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/39921',\n",
       "  'id': 812428593,\n",
       "  'node_id': 'MDU6SXNzdWU4MTI0Mjg1OTM=',\n",
       "  'number': 39921,\n",
       "  'title': 'ENH: get_rename_function: add support for __getitem__ override',\n",
       "  'user': {'login': 'philippefutureboy',\n",
       "   'id': 31741972,\n",
       "   'node_id': 'MDQ6VXNlcjMxNzQxOTcy',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/31741972?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/philippefutureboy',\n",
       "   'html_url': 'https://github.com/philippefutureboy',\n",
       "   'followers_url': 'https://api.github.com/users/philippefutureboy/followers',\n",
       "   'following_url': 'https://api.github.com/users/philippefutureboy/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/philippefutureboy/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/philippefutureboy/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/philippefutureboy/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/philippefutureboy/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/philippefutureboy/repos',\n",
       "   'events_url': 'https://api.github.com/users/philippefutureboy/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/philippefutureboy/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [{'id': 76812,\n",
       "    'node_id': 'MDU6TGFiZWw3NjgxMg==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement',\n",
       "    'name': 'Enhancement',\n",
       "    'color': '4E9A06',\n",
       "    'default': False,\n",
       "    'description': None},\n",
       "   {'id': 1954720290,\n",
       "    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',\n",
       "    'name': 'Needs Triage',\n",
       "    'color': '0052cc',\n",
       "    'default': False,\n",
       "    'description': 'Issue that has not been reviewed by a pandas team member'}],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': None,\n",
       "  'comments': 0,\n",
       "  'created_at': '2021-02-19T23:25:35Z',\n",
       "  'updated_at': '2021-02-19T23:26:17Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'NONE',\n",
       "  'active_lock_reason': None,\n",
       "  'body': '#### Is your feature request related to a problem?\\r\\n\\r\\nI would like to be able to use a subclass of UserDict with custom `__getitem__` implementation as a mapper for my dataframe columns. My use case is that I want to have a mapper with default remapping rules when the key is not present.\\r\\nUnfortunately, as the implementation checks for membership of the key before actually calling `__getitem__`, I am only able to do the behaviour by wrapping the UserDict with a lambda.\\r\\n\\r\\nCurrent implementation of get_rename_function in pandas:\\r\\n\\r\\n```\\r\\ndef get_rename_function(mapper):\\r\\n    \"\"\"\\r\\n    Returns a function that will map names/labels, dependent if mapper\\r\\n    is a dict, Series or just a function.\\r\\n    \"\"\"\\r\\n    if isinstance(mapper, (abc.Mapping, ABCSeries)):\\r\\n        def f(x):\\r\\n            if x in mapper:\\r\\n                return mapper[x]\\r\\n            else:\\r\\n                return x\\r\\n\\r\\n    else:\\r\\n        f = mapper\\r\\n\\r\\n    return f\\r\\n```\\r\\n\\r\\nMy proposition is the following:\\r\\n\\r\\n```\\r\\ndef get_rename_function(mapper):\\r\\n    \"\"\"\\r\\n    Returns a function that will map names/labels, dependent if mapper\\r\\n    is a dict, Series or just a function.\\r\\n    \"\"\"\\r\\n    if isinstance(mapper, (abc.Mapping, ABCSeries)):\\r\\n        def f(k):\\r\\n            return mapper.get(k, k)\\r\\n    else:\\r\\n        f = mapper\\r\\n\\r\\n    return f\\r\\n```\\r\\n\\r\\nwhich functionally should result in the same behaviour. \\r\\nThe advantage for me is that `__getitem__` is called and I can process k to return my default mapping.\\r\\nI don\\'t know however if this would have a significant performance impact. If so, alternatively I\\'d propose the following:\\r\\n\\r\\n```\\r\\ndef get_rename_function(mapper):\\r\\n    \"\"\"\\r\\n    Returns a function that will map names/labels, dependent if mapper\\r\\n    is a dict, Series or just a function.\\r\\n    \"\"\"\\r\\n    if not callable(mapper) and isinstance(mapper, (abc.Mapping, ABCSeries)):\\r\\n        def f(x):\\r\\n            if x in mapper:\\r\\n                return mapper[x]\\r\\n            else:\\r\\n                return x\\r\\n    else:\\r\\n        f = mapper\\r\\n\\r\\n    return f\\r\\n```\\r\\n\\r\\nThen I could implement the `__call__` method. The downside however is that this could be a breaking change for some people that pass a subclass of a Mapping as well.\\r\\n\\r\\nWhat do you think?',\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39920',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39920/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39920/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39920/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/39920',\n",
       "  'id': 812388716,\n",
       "  'node_id': 'MDU6SXNzdWU4MTIzODg3MTY=',\n",
       "  'number': 39920,\n",
       "  'title': 'BUG: \"unique\" and pd.Series.unique produce different results with aggregation',\n",
       "  'user': {'login': 'iakremnev',\n",
       "   'id': 13620282,\n",
       "   'node_id': 'MDQ6VXNlcjEzNjIwMjgy',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/13620282?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/iakremnev',\n",
       "   'html_url': 'https://github.com/iakremnev',\n",
       "   'followers_url': 'https://api.github.com/users/iakremnev/followers',\n",
       "   'following_url': 'https://api.github.com/users/iakremnev/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/iakremnev/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/iakremnev/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/iakremnev/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/iakremnev/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/iakremnev/repos',\n",
       "   'events_url': 'https://api.github.com/users/iakremnev/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/iakremnev/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [{'id': 76811,\n",
       "    'node_id': 'MDU6TGFiZWw3NjgxMQ==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',\n",
       "    'name': 'Bug',\n",
       "    'color': 'e10c02',\n",
       "    'default': False,\n",
       "    'description': None},\n",
       "   {'id': 1954720290,\n",
       "    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',\n",
       "    'name': 'Needs Triage',\n",
       "    'color': '0052cc',\n",
       "    'default': False,\n",
       "    'description': 'Issue that has not been reviewed by a pandas team member'}],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': None,\n",
       "  'comments': 0,\n",
       "  'created_at': '2021-02-19T22:11:19Z',\n",
       "  'updated_at': '2021-02-19T22:30:57Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'NONE',\n",
       "  'active_lock_reason': None,\n",
       "  'body': '- [x] I have checked that this issue has not already been reported.\\r\\n\\r\\n- [x] I have confirmed this bug exists on the latest version of pandas.\\r\\n\\r\\n- [x] (optional) I have confirmed this bug exists on the master branch of pandas.\\r\\n\\r\\n---\\r\\n\\r\\n#### Code Sample, a copy-pastable example\\r\\n\\r\\n```python\\r\\nimport pandas as pd\\r\\n\\r\\ndf = pd.DataFrame({\"a\": [1, 2, 1, 2], \"b\": [2, 1, 1, 2]})\\r\\ng = df.groupby(\"a\")\\r\\n\\r\\nfor aggfunc in [\"unique\", pd.unique, pd.Series.unique]:\\r\\n    try:\\r\\n        print(g.agg({\"b\": aggfunc}))\\r\\n    except ValueError as e:\\r\\n        print(f\"{aggfunc!r} failed with {e!r}\")\\r\\n```\\r\\n\\r\\nRunning this script produces\\r\\n\\r\\n```\\r\\n        b\\r\\na        \\r\\n1  [2, 1]\\r\\n2  [1, 2]\\r\\n<function unique at 0x7f6885cc7310> failed with ValueError(\\'Must produce aggregated value\\')\\r\\n<function Series.unique at 0x7f688369f8b0> failed with ValueError(\\'Must produce aggregated value\\')\\r\\n```\\r\\n\\r\\n#### Problem description\\r\\n\\r\\nWhen using \"unique\" str as the `aggfunc` parameter, internally it is [interpreted](https://github.com/pandas-dev/pandas/blob/v1.2.2/pandas/core/groupby/generic.py#L241) as `pd.Series.unique`. I expect identical results when passing \"unique\" and `pd.Series.unique`, or `pd.unique` but they are not.\\r\\n\\r\\n#### Output of ``pd.show_versions()``\\r\\n\\r\\n<details>\\r\\n\\r\\nINSTALLED VERSIONS\\r\\n------------------\\r\\ncommit           : f904213ffcc36d3ae29c37ae28fbb1844a0769ab\\r\\npython           : 3.9.1.final.0\\r\\npython-bits      : 64\\r\\nOS               : Linux\\r\\nOS-release       : 5.10.11-arch1-1\\r\\nVersion          : #1 SMP PREEMPT Wed, 27 Jan 2021 13:53:16 +0000\\r\\nmachine          : x86_64\\r\\nprocessor        :\\r\\nbyteorder        : little\\r\\nLC_ALL           : None\\r\\nLANG             : en_US.UTF-8\\r\\nLOCALE           : en_US.UTF-8\\r\\n\\r\\npandas           : 1.3.0.dev0+772.gf904213ffc\\r\\nnumpy            : 1.20.1\\r\\npytz             : 2021.1\\r\\ndateutil         : 2.8.1\\r\\npip              : 20.2.3\\r\\nsetuptools       : 49.2.1\\r\\nCython           : None\\r\\npytest           : None\\r\\nhypothesis       : None\\r\\nsphinx           : None\\r\\nblosc            : None\\r\\nfeather          : None\\r\\nxlsxwriter       : None\\r\\nlxml.etree       : None\\r\\nhtml5lib         : None\\r\\npymysql          : None\\r\\npsycopg2         : None\\r\\njinja2           : None\\r\\nIPython          : None\\r\\npandas_datareader: None\\r\\nbs4              : None\\r\\nbottleneck       : None\\r\\nfsspec           : None\\r\\nfastparquet      : None\\r\\ngcsfs            : None\\r\\nmatplotlib       : None\\r\\nnumexpr          : None\\r\\nodfpy            : None\\r\\nopenpyxl         : None\\r\\npandas_gbq       : None\\r\\npyarrow          : None\\r\\npyxlsb           : None\\r\\ns3fs             : None\\r\\nscipy            : None\\r\\nsqlalchemy       : None\\r\\ntables           : None\\r\\ntabulate         : None\\r\\nxarray           : None\\r\\nxlrd             : None\\r\\nxlwt             : None\\r\\nnumba            : None\\r\\n\\r\\n</details>\\r\\n',\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39919',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39919/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39919/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39919/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/pull/39919',\n",
       "  'id': 812364629,\n",
       "  'node_id': 'MDExOlB1bGxSZXF1ZXN0NTc2NzQzMDA5',\n",
       "  'number': 39919,\n",
       "  'title': 'TYP: create a Frequency alias in _typing',\n",
       "  'user': {'login': 'arw2019',\n",
       "   'id': 48889395,\n",
       "   'node_id': 'MDQ6VXNlcjQ4ODg5Mzk1',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/48889395?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/arw2019',\n",
       "   'html_url': 'https://github.com/arw2019',\n",
       "   'followers_url': 'https://api.github.com/users/arw2019/followers',\n",
       "   'following_url': 'https://api.github.com/users/arw2019/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/arw2019/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/arw2019/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/arw2019/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/arw2019/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/arw2019/repos',\n",
       "   'events_url': 'https://api.github.com/users/arw2019/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/arw2019/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [{'id': 1280988427,\n",
       "    'node_id': 'MDU6TGFiZWwxMjgwOTg4NDI3',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Typing',\n",
       "    'name': 'Typing',\n",
       "    'color': 'ea91a4',\n",
       "    'default': False,\n",
       "    'description': 'mypy type annotations'}],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': None,\n",
       "  'comments': 0,\n",
       "  'created_at': '2021-02-19T21:29:43Z',\n",
       "  'updated_at': '2021-02-19T22:22:31Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'MEMBER',\n",
       "  'active_lock_reason': None,\n",
       "  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/39919',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/pull/39919',\n",
       "   'diff_url': 'https://github.com/pandas-dev/pandas/pull/39919.diff',\n",
       "   'patch_url': 'https://github.com/pandas-dev/pandas/pull/39919.patch'},\n",
       "  'body': '- [ ] closes #xxxx\\r\\n- [ ] tests added / passed\\r\\n- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them\\r\\n- [ ] whatsnew entry\\r\\n\\r\\nSpinning off a piece of #38416',\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39917',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39917/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39917/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39917/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/pull/39917',\n",
       "  'id': 812306370,\n",
       "  'node_id': 'MDExOlB1bGxSZXF1ZXN0NTc2NjkyOTI0',\n",
       "  'number': 39917,\n",
       "  'title': 'BENCH: collect low-dependency asvs',\n",
       "  'user': {'login': 'jbrockmendel',\n",
       "   'id': 8078968,\n",
       "   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/jbrockmendel',\n",
       "   'html_url': 'https://github.com/jbrockmendel',\n",
       "   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',\n",
       "   'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/jbrockmendel/repos',\n",
       "   'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': None,\n",
       "  'comments': 0,\n",
       "  'created_at': '2021-02-19T20:12:35Z',\n",
       "  'updated_at': '2021-02-19T20:12:35Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'MEMBER',\n",
       "  'active_lock_reason': None,\n",
       "  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/39917',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/pull/39917',\n",
       "   'diff_url': 'https://github.com/pandas-dev/pandas/pull/39917.diff',\n",
       "   'patch_url': 'https://github.com/pandas-dev/pandas/pull/39917.patch'},\n",
       "  'body': 'The idea here is to collect benchmarks in such a way that we can say \"This PR doesn\\'t change code in files [...] -> We can skip running asvs in files [...]\".  (putting together a POC script to automate a bit of this)\\r\\n\\r\\nThere is a cost to refactoring benchmarks, since we have to re-run the new benchmarks on older commits (and im not sure if that happens automatically or if some human intervention is needed cc @TomAugspurger ?).  On the flip side, this is the kind of problem that we can throw hardware at, so I don\\'t worry about it that much.  Still, the bar for merging is higher than it would be for non-benchmark refactors.\\r\\n\\r\\nWith that in mind, the other refactors I\\'m looking at:\\r\\n\\r\\n1) We have benchmarks for e.g. `isin` scattered around, benchmarking `[algos.isin(x, y), pd.array(x).isin(y), Index(s).isin(y), Series(x).isin(y)]`.  I\\'d like to collect these in one place and parametrize them.\\r\\n\\r\\n2) Similar for Index methods, we have a lot of similar benchmarks for different index subclasses that id like to collect+parametrize.\\r\\n',\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39916',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39916/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39916/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39916/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/pull/39916',\n",
       "  'id': 812298537,\n",
       "  'node_id': 'MDExOlB1bGxSZXF1ZXN0NTc2Njg2MDcy',\n",
       "  'number': 39916,\n",
       "  'title': 'ENH: Implement unary operators for FloatingArray class',\n",
       "  'user': {'login': 'zitorelova',\n",
       "   'id': 18115607,\n",
       "   'node_id': 'MDQ6VXNlcjE4MTE1NjA3',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/18115607?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/zitorelova',\n",
       "   'html_url': 'https://github.com/zitorelova',\n",
       "   'followers_url': 'https://api.github.com/users/zitorelova/followers',\n",
       "   'following_url': 'https://api.github.com/users/zitorelova/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/zitorelova/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/zitorelova/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/zitorelova/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/zitorelova/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/zitorelova/repos',\n",
       "   'events_url': 'https://api.github.com/users/zitorelova/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/zitorelova/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': None,\n",
       "  'comments': 0,\n",
       "  'created_at': '2021-02-19T20:02:42Z',\n",
       "  'updated_at': '2021-02-19T23:51:40Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'CONTRIBUTOR',\n",
       "  'active_lock_reason': None,\n",
       "  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/39916',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/pull/39916',\n",
       "   'diff_url': 'https://github.com/pandas-dev/pandas/pull/39916.diff',\n",
       "   'patch_url': 'https://github.com/pandas-dev/pandas/pull/39916.patch'},\n",
       "  'body': '- [ ] closes #38749\\r\\n- [ ] tests added / passed\\r\\n- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them\\r\\n- [ ] whatsnew entry\\r\\n',\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39915',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39915/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39915/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39915/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/39915',\n",
       "  'id': 812225525,\n",
       "  'node_id': 'MDU6SXNzdWU4MTIyMjU1MjU=',\n",
       "  'number': 39915,\n",
       "  'title': 'ENH: `df.explode` should turn empty lists into *no* rows rather than a NaN row',\n",
       "  'user': {'login': 'rben01',\n",
       "   'id': 766670,\n",
       "   'node_id': 'MDQ6VXNlcjc2NjY3MA==',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/766670?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/rben01',\n",
       "   'html_url': 'https://github.com/rben01',\n",
       "   'followers_url': 'https://api.github.com/users/rben01/followers',\n",
       "   'following_url': 'https://api.github.com/users/rben01/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/rben01/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/rben01/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/rben01/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/rben01/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/rben01/repos',\n",
       "   'events_url': 'https://api.github.com/users/rben01/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/rben01/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [{'id': 76812,\n",
       "    'node_id': 'MDU6TGFiZWw3NjgxMg==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement',\n",
       "    'name': 'Enhancement',\n",
       "    'color': '4E9A06',\n",
       "    'default': False,\n",
       "    'description': None},\n",
       "   {'id': 1954720290,\n",
       "    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',\n",
       "    'name': 'Needs Triage',\n",
       "    'color': '0052cc',\n",
       "    'default': False,\n",
       "    'description': 'Issue that has not been reviewed by a pandas team member'},\n",
       "   {'id': 13098779,\n",
       "    'node_id': 'MDU6TGFiZWwxMzA5ODc3OQ==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Reshaping',\n",
       "    'name': 'Reshaping',\n",
       "    'color': '02d7e1',\n",
       "    'default': False,\n",
       "    'description': 'Concat, Merge/Join, Stack/Unstack'}],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': None,\n",
       "  'comments': 1,\n",
       "  'created_at': '2021-02-19T18:04:54Z',\n",
       "  'updated_at': '2021-02-20T03:32:05Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'NONE',\n",
       "  'active_lock_reason': None,\n",
       "  'body': \"#### Is your feature request related to a problem?\\r\\n\\r\\nWhen using `df.explode`, I'd expect that a list-like `L` gets transformed into `len(L)` rows and a scalar into 1 row. While documented, the current behavior of turning empty list-likes into 1 row containing NaN instead of 0 rows is counterintuitive.\\r\\n\\r\\n#### Describe the solution you'd like\\r\\n\\r\\nIdeally `df.explode` would transform empty list-likes into 0 rows, or, to maintain backwards compatibility, introduce an argument `collapse_empty=False` (or similar -- maybe `implode_empty` in keeping with the theme) that I could set to `True`.\\r\\n\\r\\n#### API breaking implications\\r\\n\\r\\nIf `collapse_empty=False` by default then there would be no API breaking changes.\\r\\n\\r\\n#### Describe alternatives you've considered\\r\\n\\r\\nCarefully using `df.dropna` after `df.explode` to remove any null values I don't want while preserving null values that had belonged to lists prior to the explode.\\r\\n\\r\\n#### Additional context\\r\\n\\r\\nUsing the example in the docs here: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.explode.html\\r\\n\\r\\n```python\\r\\n>>> df = pd.DataFrame({'A': [[1, 2, 3], 'foo', [], [3, 4]], 'B': 1})\\r\\n>>> df\\r\\n           A  B\\r\\n0  [1, 2, 3]  1\\r\\n1        foo  1\\r\\n2         []  1\\r\\n3     [3, 4]  1\\r\\n\\r\\n>>> df.explode('A', collapse_empty=True)\\r\\n     A  B\\r\\n0    1  1\\r\\n0    2  1\\r\\n0    3  1\\r\\n1  foo  1\\r\\n3    3  1\\r\\n3    4  1\\r\\n\\r\\n```\\r\\n\\r\\nI believe that the change would require adding a corresponding argument to [`reshape.explode`](https://github.com/pandas-dev/pandas/blob/75609da1dfcf136f9a6e2f37eff5809cacde2925/pandas/_libs/reshape.pyx#L103) and then using that argument in the length checks in lines [129](https://github.com/pandas-dev/pandas/blob/75609da1dfcf136f9a6e2f37eff5809cacde2925/pandas/_libs/reshape.pyx#L129) and [143](https://github.com/pandas-dev/pandas/blob/75609da1dfcf136f9a6e2f37eff5809cacde2925/pandas/_libs/reshape.pyx#L143). Something like this:\\r\\n\\r\\n```python\\r\\nif len(v):\\r\\n    ...\\r\\nelif not collapse_empty:\\r\\n    # empty list-like, use a nan marker\\r\\n    ...\\r\\n```\",\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39914',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39914/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39914/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39914/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/39914',\n",
       "  'id': 812209750,\n",
       "  'node_id': 'MDU6SXNzdWU4MTIyMDk3NTA=',\n",
       "  'number': 39914,\n",
       "  'title': 'ENH: Multi-layered Vector Functions',\n",
       "  'user': {'login': 'itmmckernan',\n",
       "   'id': 19756528,\n",
       "   'node_id': 'MDQ6VXNlcjE5NzU2NTI4',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/19756528?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/itmmckernan',\n",
       "   'html_url': 'https://github.com/itmmckernan',\n",
       "   'followers_url': 'https://api.github.com/users/itmmckernan/followers',\n",
       "   'following_url': 'https://api.github.com/users/itmmckernan/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/itmmckernan/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/itmmckernan/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/itmmckernan/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/itmmckernan/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/itmmckernan/repos',\n",
       "   'events_url': 'https://api.github.com/users/itmmckernan/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/itmmckernan/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [{'id': 76812,\n",
       "    'node_id': 'MDU6TGFiZWw3NjgxMg==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement',\n",
       "    'name': 'Enhancement',\n",
       "    'color': '4E9A06',\n",
       "    'default': False,\n",
       "    'description': None},\n",
       "   {'id': 2822098,\n",
       "    'node_id': 'MDU6TGFiZWwyODIyMDk4',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Indexing',\n",
       "    'name': 'Indexing',\n",
       "    'color': '0b02e1',\n",
       "    'default': False,\n",
       "    'description': 'Related to indexing on series/frames, not to indexes themselves'},\n",
       "   {'id': 1954720290,\n",
       "    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',\n",
       "    'name': 'Needs Triage',\n",
       "    'color': '0052cc',\n",
       "    'default': False,\n",
       "    'description': 'Issue that has not been reviewed by a pandas team member'}],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': None,\n",
       "  'comments': 7,\n",
       "  'created_at': '2021-02-19T17:39:36Z',\n",
       "  'updated_at': '2021-02-20T03:39:23Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'NONE',\n",
       "  'active_lock_reason': None,\n",
       "  'body': \"#### Add multi-layered vector support\\r\\nWhen working on a large panadas dataframe, I tried to use the iloc method on the dataframe with a list of lists index query. I thought that the behavior of iloc with a 1d array would be extended to 2d arrays, and it would return a 2d array of the query results. This would allow for lists of lists to be operated on inside the dataframe.\\r\\n\\r\\n#### Extending the behavior of iloc to multidimensional indexes\\r\\n\\r\\nI think that the way that iloc handles 1d arrays should be extended to 2d and possibly even higher dimensions to allow for efficient loopless code to be written. For example, passing iloc a 2d array of indices should have it return 2d array of the results.\\r\\n\\r\\n#### API breaking implications\\r\\n\\r\\nThis shouldn't break any existing code, or add any new arguments to iloc, just make the backend handle multidimensional arrays and return a multidimensional array as necessary.\\r\\n\\r\\n#### Alternatives\\r\\n\\r\\nA loop can just be made in python to achieve the same effect but will be significantly slower. While my dataset could probably be operated on with just python and some basic patience, the most ideal solution, as far as I can tell, would be this.\\r\\n\\r\\n#### Example\\r\\nThis is what could be an implementation of this could look like.\\r\\n```\\r\\nindexArray = [[0, 3, 5, 7, 9], [1, 4, 6, 8]]\\r\\n2d_result = df.iloc[indexArray]\\r\\n```\\r\\n2d_result would be an array with the shape of the indexArray populated by results from df.\",\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39913',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39913/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39913/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39913/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/39913',\n",
       "  'id': 812202688,\n",
       "  'node_id': 'MDU6SXNzdWU4MTIyMDI2ODg=',\n",
       "  'number': 39913,\n",
       "  'title': 'ENH: new orient setting for read_json to support common API format',\n",
       "  'user': {'login': 'ryancasburn-KAI',\n",
       "   'id': 63560854,\n",
       "   'node_id': 'MDQ6VXNlcjYzNTYwODU0',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/63560854?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/ryancasburn-KAI',\n",
       "   'html_url': 'https://github.com/ryancasburn-KAI',\n",
       "   'followers_url': 'https://api.github.com/users/ryancasburn-KAI/followers',\n",
       "   'following_url': 'https://api.github.com/users/ryancasburn-KAI/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/ryancasburn-KAI/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/ryancasburn-KAI/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/ryancasburn-KAI/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/ryancasburn-KAI/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/ryancasburn-KAI/repos',\n",
       "   'events_url': 'https://api.github.com/users/ryancasburn-KAI/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/ryancasburn-KAI/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [{'id': 76812,\n",
       "    'node_id': 'MDU6TGFiZWw3NjgxMg==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement',\n",
       "    'name': 'Enhancement',\n",
       "    'color': '4E9A06',\n",
       "    'default': False,\n",
       "    'description': None},\n",
       "   {'id': 49379259,\n",
       "    'node_id': 'MDU6TGFiZWw0OTM3OTI1OQ==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20JSON',\n",
       "    'name': 'IO JSON',\n",
       "    'color': '207de5',\n",
       "    'default': False,\n",
       "    'description': 'read_json, to_json, json_normalize'}],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': None,\n",
       "  'comments': 2,\n",
       "  'created_at': '2021-02-19T17:28:42Z',\n",
       "  'updated_at': '2021-02-19T20:13:35Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'NONE',\n",
       "  'active_lock_reason': None,\n",
       "  'body': '#### Is your feature request related to a problem?\\r\\n\\r\\nI see many APIs return results in the form:\\r\\n\\r\\n```json\\r\\n{\\r\\n\"results\": [\\r\\n    {\"a\" :1,\\r\\n     \"b\":2\\r\\n    },\\r\\n    {\\r\\n     \"a\" :3,\\r\\n     \"b\":4\\r\\n    }\\r\\n  ]\\r\\n}\\r\\n```\\r\\nThis format isn\\'t directly supported by pandas. The data is in the \"records\" orient, but there is an extra layer. Currently to load this file I am using the requests module to load from https, then using the json module to strip out the outer layer, then feeding this data to pd.read_json as text. This feels like overkill, since pandas can read from https, but for this format (which is common for APIs) I need multiple other packages and lines of code.\\r\\n\\r\\nThis will change a three import, multi-line issue into a single import, single line solution.\\r\\n\\r\\n#### Describe the solution you\\'d like\\r\\n\\r\\nWhile I initially describe this as a new orient, I don\\'t think that is the best way to implement this. I believe the `read_json` function should have a new parameter (such as \"strip_layer\") which will be the value of that outer layer. In the example above that would be \"results\". I make this suggestion as what is inside the outer layer could be several different orients, so we need to leave that as a possibility. This is something that happens first, then the data is processed.\\r\\n\\r\\n#### API breaking implications\\r\\n\\r\\nNeed to consider what this means for chunking.\\r\\n\\r\\n\\r\\n#### Additional context\\r\\n\\r\\nMy current code:\\r\\n\\r\\n```python\\r\\nimport pandas as pd\\r\\nimport requests\\r\\nimport json\\r\\n\\r\\ndata = requests.get(url).json()\\r\\ndata = data[\"results\"]\\r\\ndata = json.dumps(data)\\r\\ndata = pd.read_json(data)\\r\\n```\\r\\n\\r\\nversus my desired code with this improvement:\\r\\n\\r\\n```python\\r\\nimport pandas as pd\\r\\n\\r\\ndata = pd.read_json(url, strip_layer=\"results\")\\r\\n```\\r\\n\\r\\n\\r\\nMight I suggest this gets added to the IO Method Robustness/Input Types Project?',\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39911',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39911/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39911/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39911/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/39911',\n",
       "  'id': 812083542,\n",
       "  'node_id': 'MDU6SXNzdWU4MTIwODM1NDI=',\n",
       "  'number': 39911,\n",
       "  'title': 'BUG: DataFrame does not display as LaTeX in Jupyter when it should',\n",
       "  'user': {'login': 'AllenDowney',\n",
       "   'id': 1882093,\n",
       "   'node_id': 'MDQ6VXNlcjE4ODIwOTM=',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/1882093?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/AllenDowney',\n",
       "   'html_url': 'https://github.com/AllenDowney',\n",
       "   'followers_url': 'https://api.github.com/users/AllenDowney/followers',\n",
       "   'following_url': 'https://api.github.com/users/AllenDowney/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/AllenDowney/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/AllenDowney/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/AllenDowney/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/AllenDowney/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/AllenDowney/repos',\n",
       "   'events_url': 'https://api.github.com/users/AllenDowney/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/AllenDowney/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [{'id': 76811,\n",
       "    'node_id': 'MDU6TGFiZWw3NjgxMQ==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',\n",
       "    'name': 'Bug',\n",
       "    'color': 'e10c02',\n",
       "    'default': False,\n",
       "    'description': None},\n",
       "   {'id': 1954720290,\n",
       "    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',\n",
       "    'name': 'Needs Triage',\n",
       "    'color': '0052cc',\n",
       "    'default': False,\n",
       "    'description': 'Issue that has not been reviewed by a pandas team member'}],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': None,\n",
       "  'comments': 0,\n",
       "  'created_at': '2021-02-19T14:49:11Z',\n",
       "  'updated_at': '2021-02-19T14:49:11Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'CONTRIBUTOR',\n",
       "  'active_lock_reason': None,\n",
       "  'body': \"- [ X] I have checked that this issue has not already been reported.\\r\\n\\r\\n- [ X] I have confirmed this bug exists on the latest version of pandas.\\r\\n\\r\\n- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.\\r\\n\\r\\n---\\r\\n\\r\\nIf you run  the following in a Jupyter cell:\\r\\n\\r\\n```python\\r\\nimport pandas as pd\\r\\n\\r\\npd.options.display.latex.repr = True\\r\\n\\r\\nd = {'one' : [1., 2., 3., 4.],\\r\\n     'two' : [4., 3., 2., 1.]}\\r\\ndf = pd.DataFrame(d)\\r\\ndf\\r\\n```\\r\\nThe result is the HTML repr, as usual.  But if you select a column, the Series shows the LaTeX repr, as it should.\\r\\n\\r\\n```\\r\\ndf['one']\\r\\n```\\r\\n\\r\\nBut `DataFrame` has `_repr_latex_`, because this works:\\r\\n\\r\\n```\\r\\ndf._repr_latex_()\\r\\n```\\r\\n\\r\\nSo it seems like DataFrame is ignoring the `display.latex.repr` option.\\r\\n\\r\\n#### Problem description\\r\\n\\r\\nWhen `display.latex.repr` is True, DataFrames should get represented in LaTeX, not HTML.\\r\\n\\r\\n\\r\\n#### Expected Output\\r\\n\\r\\n```\\r\\n'\\\\\\\\begin{tabular}{lrr}\\\\n\\\\\\\\toprule\\\\n{} &  one &  two \\\\\\\\\\\\\\\\\\\\n\\\\\\\\midrule\\\\n0 &  1.0 &  4.0 \\\\\\\\\\\\\\\\\\\\n1 &  2.0 &  3.0 \\\\\\\\\\\\\\\\\\\\n2 &  3.0 &  2.0 \\\\\\\\\\\\\\\\\\\\n3 &  4.0 &  1.0 \\\\\\\\\\\\\\\\\\\\n\\\\\\\\bottomrule\\\\n\\\\\\\\end{tabular}\\\\n'\\r\\n```\\r\\n\\r\\n#### Output of ``pd.show_versions()``\\r\\n\\r\\n<details>\\r\\nINSTALLED VERSIONS\\r\\n------------------\\r\\ncommit           : 7d32926db8f7541c356066dcadabf854487738de\\r\\npython           : 3.7.9.final.0\\r\\npython-bits      : 64\\r\\nOS               : Linux\\r\\nOS-release       : 4.15.0-72-generic\\r\\nVersion          : #81~16.04.1-Ubuntu SMP Tue Nov 26 16:34:21 UTC 2019\\r\\nmachine          : x86_64\\r\\nprocessor        : x86_64\\r\\nbyteorder        : little\\r\\nLC_ALL           : None\\r\\nLANG             : en_US.UTF-8\\r\\nLOCALE           : en_US.UTF-8\\r\\n\\r\\npandas           : 1.2.2\\r\\nnumpy            : 1.19.2\\r\\npytz             : 2021.1\\r\\ndateutil         : 2.8.1\\r\\npip              : 21.0.1\\r\\nsetuptools       : 52.0.0.post20210125\\r\\nCython           : None\\r\\npytest           : 6.2.2\\r\\nhypothesis       : None\\r\\nsphinx           : 3.4.3\\r\\nblosc            : None\\r\\nfeather          : None\\r\\nxlsxwriter       : None\\r\\nlxml.etree       : 4.6.2\\r\\nhtml5lib         : 1.1\\r\\npymysql          : None\\r\\npsycopg2         : None\\r\\njinja2           : 2.11.3\\r\\nIPython          : 7.20.0\\r\\npandas_datareader: None\\r\\nbs4              : 4.9.3\\r\\nbottleneck       : None\\r\\nfsspec           : None\\r\\nfastparquet      : None\\r\\ngcsfs            : None\\r\\nmatplotlib       : 3.3.4\\r\\nnumexpr          : 2.7.2\\r\\nodfpy            : None\\r\\nopenpyxl         : None\\r\\npandas_gbq       : None\\r\\npyarrow          : None\\r\\npyxlsb           : None\\r\\ns3fs             : None\\r\\nscipy            : 1.6.0\\r\\nsqlalchemy       : 1.3.23\\r\\ntables           : 3.6.1\\r\\ntabulate         : None\\r\\nxarray           : None\\r\\nxlrd             : None\\r\\nxlwt             : None\\r\\nnumba            : None\\r\\n</details>\\r\\n\",\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39908',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39908/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39908/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39908/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/pull/39908',\n",
       "  'id': 812049413,\n",
       "  'node_id': 'MDExOlB1bGxSZXF1ZXN0NTc2NDc5NzEy',\n",
       "  'number': 39908,\n",
       "  'title': 'Arrow string array dtype',\n",
       "  'user': {'login': 'simonjayhawkins',\n",
       "   'id': 13159005,\n",
       "   'node_id': 'MDQ6VXNlcjEzMTU5MDA1',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/13159005?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/simonjayhawkins',\n",
       "   'html_url': 'https://github.com/simonjayhawkins',\n",
       "   'followers_url': 'https://api.github.com/users/simonjayhawkins/followers',\n",
       "   'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/simonjayhawkins/repos',\n",
       "   'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [{'id': 57522093,\n",
       "    'node_id': 'MDU6TGFiZWw1NzUyMjA5Mw==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Strings',\n",
       "    'name': 'Strings',\n",
       "    'color': '5319e7',\n",
       "    'default': False,\n",
       "    'description': 'String extension data type and string data'}],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': None,\n",
       "  'comments': 0,\n",
       "  'created_at': '2021-02-19T14:03:54Z',\n",
       "  'updated_at': '2021-02-19T16:23:10Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'MEMBER',\n",
       "  'active_lock_reason': None,\n",
       "  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/39908',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/pull/39908',\n",
       "   'diff_url': 'https://github.com/pandas-dev/pandas/pull/39908.diff',\n",
       "   'patch_url': 'https://github.com/pandas-dev/pandas/pull/39908.patch'},\n",
       "  'body': \"continuation of #36142\\r\\n\\r\\ntodo:\\r\\n\\r\\n- [ ] during the merge I removed the import gymnastics from `pandas/core/arrays/string_arrow.py`. We added since `ArrowStringDtype` should always be available. I think this is no longer the case and we want to move the import checks to `StringDtype`. I expect envs without pyarrow to fail for now.\\r\\n- [ ] `test_arrow_roundtrip` is failing. `StringDtype.__from_arrow__` needs updating.\\r\\n- [ ] address @jorisvandenbossche comments https://github.com/pandas-dev/pandas/pull/36142#discussion_r484213504 and https://github.com/pandas-dev/pandas/pull/36142#discussion_r484213103\\r\\n- [ ] some other test failures `AssertionError: assert 'unknown-array' == 'string'`\",\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39907',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39907/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39907/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39907/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/39907',\n",
       "  'id': 812032157,\n",
       "  'node_id': 'MDU6SXNzdWU4MTIwMzIxNTc=',\n",
       "  'number': 39907,\n",
       "  'title': 'BUG: wrong type hint for pandas.Series.droplevel',\n",
       "  'user': {'login': 'sz-cgt',\n",
       "   'id': 11620414,\n",
       "   'node_id': 'MDQ6VXNlcjExNjIwNDE0',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/11620414?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/sz-cgt',\n",
       "   'html_url': 'https://github.com/sz-cgt',\n",
       "   'followers_url': 'https://api.github.com/users/sz-cgt/followers',\n",
       "   'following_url': 'https://api.github.com/users/sz-cgt/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/sz-cgt/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/sz-cgt/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/sz-cgt/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/sz-cgt/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/sz-cgt/repos',\n",
       "   'events_url': 'https://api.github.com/users/sz-cgt/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/sz-cgt/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [{'id': 134699,\n",
       "    'node_id': 'MDU6TGFiZWwxMzQ2OTk=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs',\n",
       "    'name': 'Docs',\n",
       "    'color': '3465A4',\n",
       "    'default': False,\n",
       "    'description': None},\n",
       "   {'id': 717120670,\n",
       "    'node_id': 'MDU6TGFiZWw3MTcxMjA2NzA=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/good%20first%20issue',\n",
       "    'name': 'good first issue',\n",
       "    'color': '0e8a16',\n",
       "    'default': True,\n",
       "    'description': None}],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': {'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/milestone/32',\n",
       "   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32/labels',\n",
       "   'id': 933188,\n",
       "   'node_id': 'MDk6TWlsZXN0b25lOTMzMTg4',\n",
       "   'number': 32,\n",
       "   'title': 'Contributions Welcome',\n",
       "   'description': 'Changes that would be nice to have in the next release. These issues are not blocking. They will be pushed to the next release if no one has time to fix them.',\n",
       "   'creator': {'login': 'jreback',\n",
       "    'id': 953992,\n",
       "    'node_id': 'MDQ6VXNlcjk1Mzk5Mg==',\n",
       "    'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4',\n",
       "    'gravatar_id': '',\n",
       "    'url': 'https://api.github.com/users/jreback',\n",
       "    'html_url': 'https://github.com/jreback',\n",
       "    'followers_url': 'https://api.github.com/users/jreback/followers',\n",
       "    'following_url': 'https://api.github.com/users/jreback/following{/other_user}',\n",
       "    'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}',\n",
       "    'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}',\n",
       "    'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions',\n",
       "    'organizations_url': 'https://api.github.com/users/jreback/orgs',\n",
       "    'repos_url': 'https://api.github.com/users/jreback/repos',\n",
       "    'events_url': 'https://api.github.com/users/jreback/events{/privacy}',\n",
       "    'received_events_url': 'https://api.github.com/users/jreback/received_events',\n",
       "    'type': 'User',\n",
       "    'site_admin': False},\n",
       "   'open_issues': 1144,\n",
       "   'closed_issues': 670,\n",
       "   'state': 'open',\n",
       "   'created_at': '2015-01-13T10:53:19Z',\n",
       "   'updated_at': '2021-02-20T03:41:30Z',\n",
       "   'due_on': None,\n",
       "   'closed_at': None},\n",
       "  'comments': 1,\n",
       "  'created_at': '2021-02-19T13:39:51Z',\n",
       "  'updated_at': '2021-02-20T03:41:30Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'NONE',\n",
       "  'active_lock_reason': None,\n",
       "  'body': '- [X] I have checked that this issue has not already been reported.\\r\\n\\r\\n- [X] I have confirmed this bug exists on the latest version of pandas.\\r\\n\\r\\n- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.\\r\\n\\r\\n---\\r\\n\\r\\n**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.\\r\\n\\r\\n#### Code Sample, a copy-pastable example\\r\\n\\r\\n```python\\r\\ntype(pandas.Series({(\"a\", 1): 1, (\"a\", 2): 2, (\"b\", 1): 3, (\"b\", 4): 4}).droplevel(level=1))\\r\\n\\r\\n```\\r\\n\\r\\n#### Problem description\\r\\n\\r\\nBoth the type hint for pandas.Series.droplevel() and the documentation say the function returns a DataFrame.\\r\\n\\r\\nHowever, it clearly returns a Series.\\r\\n\\r\\nWhile not a Bug per se, this does violate the Law of Least Suprise\\r\\n\\r\\n#### Output of ``pd.show_versions()``\\r\\n\\r\\n<details>\\r\\n\\r\\n>>> pandas.show_versions()\\r\\n\\r\\nINSTALLED VERSIONS\\r\\n------------------\\r\\ncommit           : 7d32926db8f7541c356066dcadabf854487738de\\r\\npython           : 3.8.5.final.0\\r\\npython-bits      : 64\\r\\nOS               : Linux\\r\\nOS-release       : 4.19.104-microsoft-standard\\r\\nVersion          : #1 SMP Wed Feb 19 06:37:35 UTC 2020\\r\\nmachine          : x86_64\\r\\nprocessor        : x86_64\\r\\nbyteorder        : little\\r\\nLC_ALL           : None\\r\\nLANG             : C.UTF-8\\r\\nLOCALE           : en_US.UTF-8\\r\\n\\r\\npandas           : 1.2.2\\r\\nnumpy            : 1.20.1\\r\\npytz             : 2021.1\\r\\ndateutil         : 2.8.1\\r\\npip              : 20.0.2\\r\\nsetuptools       : 44.0.0\\r\\nCython           : None\\r\\npytest           : None\\r\\nhypothesis       : None\\r\\nsphinx           : None\\r\\nblosc            : None\\r\\nfeather          : None\\r\\nxlsxwriter       : None\\r\\nlxml.etree       : None\\r\\nhtml5lib         : 1.0.1\\r\\npymysql          : None\\r\\npsycopg2         : None\\r\\njinja2           : None\\r\\nIPython          : None\\r\\npandas_datareader: None\\r\\nbs4              : None\\r\\nbottleneck       : None\\r\\nfsspec           : None\\r\\nfastparquet      : None\\r\\ngcsfs            : None\\r\\nmatplotlib       : None\\r\\nnumexpr          : None\\r\\nodfpy            : None\\r\\nopenpyxl         : 3.0.6\\r\\npandas_gbq       : None\\r\\npyarrow          : 0.17.1\\r\\npyxlsb           : None\\r\\ns3fs             : None\\r\\nscipy            : None\\r\\nsqlalchemy       : None\\r\\ntables           : None\\r\\ntabulate         : None\\r\\nxarray           : None\\r\\nxlrd             : None\\r\\nxlwt             : None\\r\\nnumba            : None\\r\\n\\r\\n</details>\\r\\n',\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39906',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39906/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39906/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39906/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/39906',\n",
       "  'id': 811932640,\n",
       "  'node_id': 'MDU6SXNzdWU4MTE5MzI2NDA=',\n",
       "  'number': 39906,\n",
       "  'title': 'BUG: pd.read_csv ignores columns with only zeros',\n",
       "  'user': {'login': 'JustinGuese',\n",
       "   'id': 9588843,\n",
       "   'node_id': 'MDQ6VXNlcjk1ODg4NDM=',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/9588843?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/JustinGuese',\n",
       "   'html_url': 'https://github.com/JustinGuese',\n",
       "   'followers_url': 'https://api.github.com/users/JustinGuese/followers',\n",
       "   'following_url': 'https://api.github.com/users/JustinGuese/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/JustinGuese/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/JustinGuese/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/JustinGuese/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/JustinGuese/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/JustinGuese/repos',\n",
       "   'events_url': 'https://api.github.com/users/JustinGuese/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/JustinGuese/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [{'id': 76811,\n",
       "    'node_id': 'MDU6TGFiZWw3NjgxMQ==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',\n",
       "    'name': 'Bug',\n",
       "    'color': 'e10c02',\n",
       "    'default': False,\n",
       "    'description': None},\n",
       "   {'id': 47229171,\n",
       "    'node_id': 'MDU6TGFiZWw0NzIyOTE3MQ==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20CSV',\n",
       "    'name': 'IO CSV',\n",
       "    'color': '5319e7',\n",
       "    'default': False,\n",
       "    'description': None},\n",
       "   {'id': 307649777,\n",
       "    'node_id': 'MDU6TGFiZWwzMDc2NDk3Nzc=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Info',\n",
       "    'name': 'Needs Info',\n",
       "    'color': '207de5',\n",
       "    'default': False,\n",
       "    'description': 'Clarification about behavior needed to assess issue'}],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': None,\n",
       "  'comments': 1,\n",
       "  'created_at': '2021-02-19T11:11:08Z',\n",
       "  'updated_at': '2021-02-19T20:27:40Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'NONE',\n",
       "  'active_lock_reason': None,\n",
       "  'body': '- [X] I have checked that this issue has not already been reported.\\r\\n\\r\\n- [X] I have confirmed this bug exists on the latest version of pandas.\\r\\n\\r\\n- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.\\r\\n\\r\\n---\\r\\n\\r\\n**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.\\r\\n\\r\\n#### Code Sample, a copy-pastable example\\r\\n\\r\\n```python\\r\\ncolumns = [\"type\", \"symbol\", \"Date\", \"Time\", \"TSNumber\", \"Price\", \"Quantity\", \"SettlementDate\", \"Yield\", \"AccruedInterest\", \"ConditionCodes\", \"QuotationBasis\", \"ExchangeRate\", \"TradeAttributes\"]\\r\\ndf = pd.read_csv(\"20200803.csv\",dtype = str,names=columns)\\r\\n\\r\\n```\\r\\n\\r\\n#### Problem description\\r\\n\\r\\nReading in a csv file with the following line\\r\\nT,FMG,20200803,000000,10071068,,,20200804,,,XT,,,,\\r\\nresults in pandas ignoring the 4th column, and matches the current column to the next value (10071068) in that case. \\r\\n\\r\\nPrevious reports suggested setting the dtype to string (see https://stackoverflow.com/questions/13250046/how-to-keep-leading-zeros-in-a-column-when-reading-csv-with-pandas), which should be fine if the column is read in as \"0000000\", but apparently it is not. Am I missing something?\\r\\n\\r\\nCurrent output:\\r\\n\\r\\n-- | -- | -- | -- | --\\r\\n71068 | FMG | 20200803 | 10071068 | 20200803.0 ...\\r\\n\\r\\n#### Expected Output\\r\\n\\r\\n-- | -- | -- | -- | --\\r\\n71068 | FMG | 20200803 | 000000 | 10071068 | 20200803.0 ...\\r\\n\\r\\n#### Output of ``pd.show_versions()``\\r\\n\\r\\n<details>\\r\\n\\r\\n\\r\\nINSTALLED VERSIONS\\r\\n------------------\\r\\ncommit           : 67a3d4241ab84419856b84fc3ebc9abcbe66c6b3\\r\\npython           : 3.8.5.final.0\\r\\npython-bits      : 64\\r\\nOS               : Linux\\r\\nOS-release       : 5.8.0-7642-generic\\r\\nVersion          : #47~1612288990~20.04~b8113e7-Ubuntu SMP Wed Feb 3 02:25:36 UTC 2\\r\\nmachine          : x86_64\\r\\nprocessor        : x86_64\\r\\nbyteorder        : little\\r\\nLC_ALL           : None\\r\\nLANG             : en_US.UTF-8\\r\\nLOCALE           : en_US.UTF-8\\r\\n\\r\\npandas           : 1.1.4\\r\\nnumpy            : 1.19.4\\r\\npytz             : 2020.4\\r\\ndateutil         : 2.8.1\\r\\npip              : 20.3.3\\r\\nsetuptools       : 51.3.3.post20210118\\r\\nCython           : None\\r\\npytest           : None\\r\\nhypothesis       : None\\r\\nsphinx           : None\\r\\nblosc            : None\\r\\nfeather          : None\\r\\nxlsxwriter       : None\\r\\nlxml.etree       : 4.6.2\\r\\nhtml5lib         : None\\r\\npymysql          : None\\r\\npsycopg2         : None\\r\\njinja2           : 2.11.2\\r\\nIPython          : 7.19.0\\r\\npandas_datareader: None\\r\\nbs4              : 4.9.3\\r\\nbottleneck       : None\\r\\nfsspec           : None\\r\\nfastparquet      : 0.5.0\\r\\ngcsfs            : None\\r\\nmatplotlib       : None\\r\\nnumexpr          : None\\r\\nodfpy            : None\\r\\nopenpyxl         : 3.0.6\\r\\npandas_gbq       : None\\r\\npyarrow          : None\\r\\npytables         : None\\r\\npyxlsb           : None\\r\\ns3fs             : None\\r\\nscipy            : None\\r\\nsqlalchemy       : 1.3.22\\r\\ntables           : None\\r\\ntabulate         : None\\r\\nxarray           : None\\r\\nxlrd             : 2.0.1\\r\\nxlwt             : None\\r\\nnumba            : 0.52.0\\r\\n\\r\\n</details>\\r\\n',\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39904',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39904/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39904/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39904/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/39904',\n",
       "  'id': 811894956,\n",
       "  'node_id': 'MDU6SXNzdWU4MTE4OTQ5NTY=',\n",
       "  'number': 39904,\n",
       "  'title': 'BUG: DataFrame construction with columns argument set to a MultiIndex creates an empty DataFrame.',\n",
       "  'user': {'login': 'DriesSchaumont',\n",
       "   'id': 5946712,\n",
       "   'node_id': 'MDQ6VXNlcjU5NDY3MTI=',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/5946712?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/DriesSchaumont',\n",
       "   'html_url': 'https://github.com/DriesSchaumont',\n",
       "   'followers_url': 'https://api.github.com/users/DriesSchaumont/followers',\n",
       "   'following_url': 'https://api.github.com/users/DriesSchaumont/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/DriesSchaumont/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/DriesSchaumont/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/DriesSchaumont/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/DriesSchaumont/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/DriesSchaumont/repos',\n",
       "   'events_url': 'https://api.github.com/users/DriesSchaumont/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/DriesSchaumont/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [{'id': 76811,\n",
       "    'node_id': 'MDU6TGFiZWw3NjgxMQ==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',\n",
       "    'name': 'Bug',\n",
       "    'color': 'e10c02',\n",
       "    'default': False,\n",
       "    'description': None},\n",
       "   {'id': 2365504893,\n",
       "    'node_id': 'MDU6TGFiZWwyMzY1NTA0ODkz',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Closing%20Candidate',\n",
       "    'name': 'Closing Candidate',\n",
       "    'color': 'be21f2',\n",
       "    'default': False,\n",
       "    'description': 'May be closeable, needs more eyeballs'}],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': None,\n",
       "  'comments': 3,\n",
       "  'created_at': '2021-02-19T10:19:36Z',\n",
       "  'updated_at': '2021-02-20T03:59:39Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'NONE',\n",
       "  'active_lock_reason': None,\n",
       "  'body': '- [x] I have checked that this issue has not already been reported.\\r\\n\\r\\n- [x] I have confirmed this bug exists on the latest version of pandas.\\r\\n\\r\\n- [x] (optional) I have confirmed this bug exists on the master branch of pandas.\\r\\n\\r\\n---\\r\\n\\r\\n**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.\\r\\n\\r\\n#### Code Sample, a copy-pastable example\\r\\n\\r\\n```python\\r\\n>>> import pandas as pd\\r\\n>>> from numpy import nan\\r\\n>>>\\r\\n>>>\\r\\n>>> column_index = pd.MultiIndex.from_product([[\"sample1\", \"sample2\"], [True], [True]],\\r\\n...                                           names=[\"Name\", \"Sample_column\", \"Write\"])\\r\\n>>> table = pd.DataFrame(data={\"sample1\": [100.0, nan, 100.0, 10.0],\\r\\n...                            \"sample2\": [80.0, 20.0, 100.0, 100.0]})\\r\\n>>> table.columns = column_index\\r\\n>>>\\r\\n>>> table2 = pd.DataFrame(data={\"sample1\": [100.0, nan, 100.0, 10.0],\\r\\n...                             \"sample2\": [80.0, 20.0, 100.0, 100.0]},\\r\\n...                             columns=column_index)\\r\\n>>> table\\r\\nName          sample1 sample2\\r\\nSample_column    True    True\\r\\nWrite            True    True\\r\\n0               100.0    80.0\\r\\n1                 NaN    20.0\\r\\n2               100.0   100.0\\r\\n3                10.0   100.0\\r\\n>>> table2\\r\\nEmpty DataFrame\\r\\nColumns: [(sample1, True, True), (sample2, True, True)]\\r\\nIndex:\\r\\n```\\r\\n\\r\\n#### Problem description\\r\\n\\r\\nIf a MultiIndex is used to set the columns using the columns argument from the constructor, the MultiIndex is set correctly but the whole dataframe becomes empty. If the columns index is applied manually after construction by using df.columns, the dataframe does not lose its data. I think this is either a bug, or a clear warning or error message should be given why the dataframe becomes empty.\\r\\n\\r\\n#### Expected Output\\r\\n\\r\\nI expect the constructor to return a non-empty dataframe with the MultiIndex applied to the columns. The API reference mentions that is can be an \\'Index or array-like\\', but I don\\'t know if a MultiIndex is allowed.\\r\\n\\r\\n#### Output of ``pd.show_versions()``\\r\\n\\r\\n<details>\\r\\n\\r\\n>>> pd.show_versions()\\r\\n\\r\\nINSTALLED VERSIONS\\r\\n------------------\\r\\ncommit           : 7d32926db8f7541c356066dcadabf854487738de\\r\\npython           : 3.8.5.final.0\\r\\npython-bits      : 64\\r\\nOS               : Linux\\r\\nOS-release       : 5.4.0-58-generic\\r\\nVersion          : #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020\\r\\nmachine          : x86_64\\r\\nprocessor        : x86_64\\r\\nbyteorder        : little\\r\\nLC_ALL           : None\\r\\nLANG             : en_US.UTF-8\\r\\nLOCALE           : en_US.UTF-8\\r\\n\\r\\npandas           : 1.2.2\\r\\nnumpy            : 1.20.1\\r\\npytz             : 2021.1\\r\\ndateutil         : 2.8.1\\r\\npip              : 20.0.2\\r\\nsetuptools       : 44.0.0\\r\\nCython           : None\\r\\npytest           : None\\r\\nhypothesis       : None\\r\\nsphinx           : None\\r\\nblosc            : None\\r\\nfeather          : None\\r\\nxlsxwriter       : None\\r\\nlxml.etree       : None\\r\\nhtml5lib         : None\\r\\npymysql          : None\\r\\npsycopg2         : None\\r\\njinja2           : None\\r\\nIPython          : None\\r\\npandas_datareader: None\\r\\nbs4              : None\\r\\nbottleneck       : None\\r\\nfsspec           : None\\r\\nfastparquet      : None\\r\\ngcsfs            : None\\r\\nmatplotlib       : None\\r\\nnumexpr          : None\\r\\nodfpy            : None\\r\\nopenpyxl         : None\\r\\npandas_gbq       : None\\r\\npyarrow          : None\\r\\npyxlsb           : None\\r\\ns3fs             : None\\r\\nscipy            : None\\r\\nsqlalchemy       : None\\r\\ntables           : None\\r\\ntabulate         : None\\r\\nxarray           : None\\r\\nxlrd             : None\\r\\nxlwt             : None\\r\\nnumba            : None\\r\\n\\r\\n</details>\\r\\n',\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39903',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39903/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39903/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39903/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/39903',\n",
       "  'id': 811872951,\n",
       "  'node_id': 'MDU6SXNzdWU4MTE4NzI5NTE=',\n",
       "  'number': 39903,\n",
       "  'title': 'BUG: Inconsistency in df.sum when strings are present in column values',\n",
       "  'user': {'login': 'gurukiran07',\n",
       "   'id': 47276342,\n",
       "   'node_id': 'MDQ6VXNlcjQ3Mjc2MzQy',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/47276342?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/gurukiran07',\n",
       "   'html_url': 'https://github.com/gurukiran07',\n",
       "   'followers_url': 'https://api.github.com/users/gurukiran07/followers',\n",
       "   'following_url': 'https://api.github.com/users/gurukiran07/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/gurukiran07/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/gurukiran07/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/gurukiran07/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/gurukiran07/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/gurukiran07/repos',\n",
       "   'events_url': 'https://api.github.com/users/gurukiran07/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/gurukiran07/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [{'id': 76811,\n",
       "    'node_id': 'MDU6TGFiZWw3NjgxMQ==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',\n",
       "    'name': 'Bug',\n",
       "    'color': 'e10c02',\n",
       "    'default': False,\n",
       "    'description': None},\n",
       "   {'id': 233160,\n",
       "    'node_id': 'MDU6TGFiZWwyMzMxNjA=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Groupby',\n",
       "    'name': 'Groupby',\n",
       "    'color': '729FCF',\n",
       "    'default': False,\n",
       "    'description': None},\n",
       "   {'id': 2365523662,\n",
       "    'node_id': 'MDU6TGFiZWwyMzY1NTIzNjYy',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Nuisance%20Columns',\n",
       "    'name': 'Nuisance Columns',\n",
       "    'color': '120491',\n",
       "    'default': False,\n",
       "    'description': 'Identifying/Dropping nuisance columns in reductions, groupby.add, DataFrame.apply'}],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': None,\n",
       "  'comments': 1,\n",
       "  'created_at': '2021-02-19T09:50:26Z',\n",
       "  'updated_at': '2021-02-20T04:02:18Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'CONTRIBUTOR',\n",
       "  'active_lock_reason': None,\n",
       "  'body': \"- [X] I have checked that this issue has not already been reported.\\r\\n- [X] I have confirmed this bug exists on the latest version of pandas.\\r\\n- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.\\r\\n\\r\\n---\\r\\n\\r\\n#### Code Sample, a copy-pastable example\\r\\nFrom [StackOverflow question posted by Usal](https://stackoverflow.com/q/66274713/12416453)\\r\\n```python\\r\\ndf=pd.DataFrame({'Col1':[1, '-','-'], 'Col2':['-','-',2]})\\r\\ndf.sum(axis=1)\\r\\n# 0    0.0\\r\\n# 1    0.0\\r\\n# 2    0.0\\r\\n# dtype: float64\\r\\n\\r\\ndf.sum(axis=0)\\r\\n# Series([], dtype: float64)\\r\\n```\\r\\n\\r\\n#### Problem description\\r\\n\\r\\nInconsistent output when same operation i.e. `df.sum` is applied over axis 0 and 1.\\r\\n#### Expected Output\\r\\n```\\r\\ndf.sum(axis=0)\\r\\n# Col1 0.0\\r\\n# Col2 0.0\\r\\n# dtype: float64\\r\\n\\r\\ndf.sum(axis=1)\\r\\n# 0 0.0\\r\\n# 1 0.0\\r\\n# 2 0.0\\r\\n# dtype: float64\\r\\n```\\r\\n\\r\\n#### Output of ``pd.show_versions()``\\r\\n\\r\\n<details>\\r\\n<pre><code>\\r\\nINSTALLED VERSIONS\\r\\n------------------\\r\\ncommit           : 7d32926db8f7541c356066dcadabf854487738de\\r\\npython           : 3.8.5.final.0\\r\\npython-bits      : 64\\r\\nOS               : Linux\\r\\nOS-release       : 5.8.0-43-generic\\r\\nVersion          : #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021\\r\\nmachine          : x86_64\\r\\nprocessor        : x86_64\\r\\nbyteorder        : little\\r\\nLC_ALL           : None\\r\\nLANG             : en_IN\\r\\nLOCALE           : en_IN.ISO8859-1\\r\\n\\r\\npandas           : 1.2.2\\r\\nnumpy            : 1.19.5\\r\\npytz             : 2019.3\\r\\ndateutil         : 2.7.3\\r\\npip              : 20.0.2\\r\\nsetuptools       : 45.2.0\\r\\nCython           : None\\r\\npytest           : None\\r\\nhypothesis       : None\\r\\nsphinx           : None\\r\\nblosc            : None\\r\\nfeather          : None\\r\\nxlsxwriter       : None\\r\\nlxml.etree       : None\\r\\nhtml5lib         : 1.0.1\\r\\npymysql          : None\\r\\npsycopg2         : None\\r\\njinja2           : 2.10.1\\r\\nIPython          : 7.13.0\\r\\npandas_datareader: None\\r\\nbs4              : None\\r\\nbottleneck       : None\\r\\nfsspec           : None\\r\\nfastparquet      : None\\r\\ngcsfs            : None\\r\\nmatplotlib       : 3.1.2\\r\\nnumexpr          : None\\r\\nodfpy            : None\\r\\nopenpyxl         : None\\r\\npandas_gbq       : None\\r\\npyarrow          : None\\r\\npyxlsb           : None\\r\\ns3fs             : None\\r\\nscipy            : None\\r\\nsqlalchemy       : None\\r\\ntables           : None\\r\\ntabulate         : None\\r\\nxarray           : None\\r\\nxlrd             : None\\r\\nxlwt             : None\\r\\nnumba            : None\\r\\n</code></pre>\\r\\n\\r\\n</details>\\r\\n\",\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39899',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39899/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39899/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39899/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/39899',\n",
       "  'id': 811591723,\n",
       "  'node_id': 'MDU6SXNzdWU4MTE1OTE3MjM=',\n",
       "  'number': 39899,\n",
       "  'title': 'BUG: pandas.DataFrame.compare causes loss of accuracy for big ints',\n",
       "  'user': {'login': 'yuhan-wang',\n",
       "   'id': 4433420,\n",
       "   'node_id': 'MDQ6VXNlcjQ0MzM0MjA=',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/4433420?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/yuhan-wang',\n",
       "   'html_url': 'https://github.com/yuhan-wang',\n",
       "   'followers_url': 'https://api.github.com/users/yuhan-wang/followers',\n",
       "   'following_url': 'https://api.github.com/users/yuhan-wang/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/yuhan-wang/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/yuhan-wang/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/yuhan-wang/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/yuhan-wang/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/yuhan-wang/repos',\n",
       "   'events_url': 'https://api.github.com/users/yuhan-wang/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/yuhan-wang/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [{'id': 76811,\n",
       "    'node_id': 'MDU6TGFiZWw3NjgxMQ==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',\n",
       "    'name': 'Bug',\n",
       "    'color': 'e10c02',\n",
       "    'default': False,\n",
       "    'description': None},\n",
       "   {'id': 31404521,\n",
       "    'node_id': 'MDU6TGFiZWwzMTQwNDUyMQ==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Dtypes',\n",
       "    'name': 'Dtypes',\n",
       "    'color': 'e102d8',\n",
       "    'default': False,\n",
       "    'description': None}],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': None,\n",
       "  'comments': 2,\n",
       "  'created_at': '2021-02-19T00:53:20Z',\n",
       "  'updated_at': '2021-02-20T02:47:28Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'NONE',\n",
       "  'active_lock_reason': None,\n",
       "  'body': \"- [x] I have checked that this issue has not already been reported.\\r\\n\\r\\n- [x] I have confirmed this bug exists on the latest version of pandas.\\r\\n\\r\\n- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.\\r\\n\\r\\n---\\r\\n\\r\\n**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.\\r\\n\\r\\n#### Code Sample, a copy-pastable example\\r\\n\\r\\n```python\\r\\n# Your code here\\r\\nimport pandas as pd\\r\\nleft = pd.DataFrame({'a':[1567808378753000000], 'b':[0]})\\r\\nright = pd.DataFrame({'a':[1567808378753274000], 'b':[0]})\\r\\nprint(left.compare(right))\\r\\n```\\r\\n\\r\\n#### Problem description\\r\\nThe current output is\\r\\n```\\r\\n\\r\\n                     a                     \\r\\n                  self                other\\r\\n0  1567808378752999936  1567808378753274112\\r\\n```\\r\\nwhich differs from the values in the original dataframe.\\r\\n[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]\\r\\n\\r\\n#### Expected Output\\r\\n\\r\\n                     a                     \\r\\n                  self                other\\r\\n0  1567808378753000000  1567808378753274000\\r\\n#### Output of ``pd.show_versions()``\\r\\n<details>\\r\\n\\r\\n[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]\\r\\nINSTALLED VERSIONS\\r\\n------------------\\r\\ncommit           : 7d32926db8f7541c356066dcadabf854487738de\\r\\npython           : 3.8.7.final.0\\r\\npython-bits      : 64\\r\\nOS               : Linux\\r\\nOS-release       : 5.4.0-1036-gcp\\r\\nVersion          : #39-Ubuntu SMP Thu Jan 14 18:41:17 UTC 2021\\r\\nmachine          : x86_64\\r\\nprocessor        : x86_64\\r\\nbyteorder        : little\\r\\nLC_ALL           : en_US.UTF-8\\r\\nLANG             : en_US.UTF-8\\r\\nLOCALE           : en_US.UTF-8\\r\\n\\r\\npandas           : 1.2.2\\r\\nnumpy            : 1.20.1\\r\\npytz             : 2021.1\\r\\ndateutil         : 2.8.1\\r\\npip              : 19.3.1\\r\\nsetuptools       : 49.2.1\\r\\nCython           : None\\r\\npytest           : None\\r\\nhypothesis       : None\\r\\nsphinx           : None\\r\\nblosc            : None\\r\\nfeather          : None\\r\\nxlsxwriter       : None\\r\\nlxml.etree       : None\\r\\nhtml5lib         : 1.1\\r\\npymysql          : None\\r\\npsycopg2         : None\\r\\njinja2           : 2.11.2\\r\\nIPython          : None\\r\\npandas_datareader: None\\r\\nbs4              : None\\r\\nbottleneck       : None\\r\\nfsspec           : None\\r\\nfastparquet      : None\\r\\ngcsfs            : None\\r\\nmatplotlib       : 3.3.3\\r\\nnumexpr          : None\\r\\nodfpy            : None\\r\\nopenpyxl         : None\\r\\npandas_gbq       : None\\r\\npyarrow          : None\\r\\npyxlsb           : None\\r\\ns3fs             : None\\r\\nscipy            : 1.4.1\\r\\nsqlalchemy       : 1.3.22\\r\\ntables           : None\\r\\ntabulate         : None\\r\\nxarray           : None\\r\\nxlrd             : None\\r\\nxlwt             : None\\r\\nnumba            : None\\r\\n</details>\\r\\n\",\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39898',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39898/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39898/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39898/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/39898',\n",
       "  'id': 811564009,\n",
       "  'node_id': 'MDU6SXNzdWU4MTE1NjQwMDk=',\n",
       "  'number': 39898,\n",
       "  'title': 'BUG: dtype ignored in pd.read_excel',\n",
       "  'user': {'login': 'mvacher',\n",
       "   'id': 599745,\n",
       "   'node_id': 'MDQ6VXNlcjU5OTc0NQ==',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/599745?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/mvacher',\n",
       "   'html_url': 'https://github.com/mvacher',\n",
       "   'followers_url': 'https://api.github.com/users/mvacher/followers',\n",
       "   'following_url': 'https://api.github.com/users/mvacher/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/mvacher/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/mvacher/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/mvacher/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/mvacher/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/mvacher/repos',\n",
       "   'events_url': 'https://api.github.com/users/mvacher/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/mvacher/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [{'id': 31404521,\n",
       "    'node_id': 'MDU6TGFiZWwzMTQwNDUyMQ==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Dtypes',\n",
       "    'name': 'Dtypes',\n",
       "    'color': 'e102d8',\n",
       "    'default': False,\n",
       "    'description': None},\n",
       "   {'id': 34444536,\n",
       "    'node_id': 'MDU6TGFiZWwzNDQ0NDUzNg==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Usage%20Question',\n",
       "    'name': 'Usage Question',\n",
       "    'color': '0052cc',\n",
       "    'default': False,\n",
       "    'description': None}],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': None,\n",
       "  'comments': 3,\n",
       "  'created_at': '2021-02-18T23:52:45Z',\n",
       "  'updated_at': '2021-02-20T03:28:37Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'NONE',\n",
       "  'active_lock_reason': None,\n",
       "  'body': \"I'm trying to read an excel file with pd.read_excel(). \\r\\nThe excel file has 2 columns Date and Time and I want to read both columns as str not the excel dtype.\\r\\n\\r\\n\\r\\nExample of the excel file\\r\\n[test1.xlsx](https://github.com/pandas-dev/pandas/files/6006593/test1.xlsx)\\r\\n\\r\\n\\r\\nWhen using the dtype or the converters arguments the dtype of the columns remain the same\\r\\n\\r\\n```\\r\\ndf = pd.read_excel('xls_test.xlsx',\\r\\n                   dtype={'Date':str,'Time':str})\\r\\ndf.dtypes\\r\\nDate    object\\r\\nTime    object\\r\\ndtype: object\\r\\n```\\r\\n```\\r\\ndf.head()\\r\\nDate\\tTime\\r\\n0\\t2020-03-08 00:00:00\\t10:00:00\\r\\n1\\t2020-03-09 00:00:00\\t11:00:00\\r\\n2\\t2020-03-10 00:00:00\\t12:00:00\\r\\n3\\t2020-03-11 00:00:00\\t13:00:00\\r\\n4\\t2020-03-12 00:00:00\\t14:00:00\\r\\n\\r\\n```\\r\\n\\r\\nSame thing when using converters\\r\\n\\r\\n```\\r\\ndf = pd.read_excel('xls_test.xlsx',\\r\\n                   converters={'Date':str,'Time':str})\\r\\ndf.dtypes\\r\\nDate    object\\r\\nTime    object\\r\\ndtype: object\\r\\n```\\r\\n```\\r\\ndf.head()\\r\\nDate\\tTime\\r\\n0\\t2020-03-08 00:00:00\\t10:00:00\\r\\n1\\t2020-03-09 00:00:00\\t11:00:00\\r\\n2\\t2020-03-10 00:00:00\\t12:00:00\\r\\n3\\t2020-03-11 00:00:00\\t13:00:00\\r\\n4\\t2020-03-12 00:00:00\\t14:00:00\\r\\n\\r\\n```\\r\\n\\r\\nI have also tried to use other engine but the result is always the same.\\r\\n\\r\\n\\r\\n### pd.show_versions()\\r\\n\\r\\n```\\r\\nINSTALLED VERSIONS\\r\\n------------------\\r\\ncommit           : 7d32926db8f7541c356066dcadabf854487738de\\r\\npython           : 3.8.5.final.0\\r\\npython-bits      : 64\\r\\nOS               : Darwin\\r\\nOS-release       : 20.2.0\\r\\nVersion          : Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64\\r\\nmachine          : x86_64\\r\\nprocessor        : i386\\r\\nbyteorder        : little\\r\\nLC_ALL           : None\\r\\nLANG             : en_AU.UTF-8\\r\\nLOCALE           : en_AU.UTF-8\\r\\n\\r\\npandas           : 1.2.2\\r\\nnumpy            : 1.20.1\\r\\npytz             : 2020.1\\r\\ndateutil         : 2.8.1\\r\\npip              : 21.0.1\\r\\nsetuptools       : 50.3.1.post20201107\\r\\nCython           : 0.29.21\\r\\npytest           : 6.1.1\\r\\nhypothesis       : None\\r\\nsphinx           : 3.2.1\\r\\nblosc            : None\\r\\nfeather          : None\\r\\nxlsxwriter       : 1.3.7\\r\\nlxml.etree       : 4.6.1\\r\\nhtml5lib         : 1.1\\r\\npymysql          : None\\r\\npsycopg2         : None\\r\\njinja2           : 2.11.2\\r\\nIPython          : 7.19.0\\r\\npandas_datareader: None\\r\\nbs4              : 4.9.3\\r\\nbottleneck       : 1.3.2\\r\\nfsspec           : 0.8.3\\r\\nfastparquet      : None\\r\\ngcsfs            : None\\r\\nmatplotlib       : 3.3.2\\r\\nnumexpr          : 2.7.1\\r\\nodfpy            : None\\r\\nopenpyxl         : 3.0.6\\r\\npandas_gbq       : None\\r\\npyarrow          : None\\r\\npyxlsb           : 1.0.8\\r\\ns3fs             : None\\r\\nscipy            : 1.5.2\\r\\nsqlalchemy       : 1.3.20\\r\\ntables           : 3.6.1\\r\\ntabulate         : None\\r\\nxarray           : None\\r\\nxlrd             : 1.2.0\\r\\nxlwt             : 1.3.0\\r\\nnumba            : 0.52.0\\r\\n```\\r\\n\\r\\nThis seems too obvious to be an unreported bug and I apologise if the problem comes from my side.\",\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39897',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39897/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39897/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39897/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/pull/39897',\n",
       "  'id': 811511801,\n",
       "  'node_id': 'MDExOlB1bGxSZXF1ZXN0NTc2MDI5NzEx',\n",
       "  'number': 39897,\n",
       "  'title': 'TYP: indexes/base.py',\n",
       "  'user': {'login': 'topper-123',\n",
       "   'id': 26364415,\n",
       "   'node_id': 'MDQ6VXNlcjI2MzY0NDE1',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/26364415?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/topper-123',\n",
       "   'html_url': 'https://github.com/topper-123',\n",
       "   'followers_url': 'https://api.github.com/users/topper-123/followers',\n",
       "   'following_url': 'https://api.github.com/users/topper-123/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/topper-123/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/topper-123/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/topper-123/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/topper-123/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/topper-123/repos',\n",
       "   'events_url': 'https://api.github.com/users/topper-123/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/topper-123/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [{'id': 1280988427,\n",
       "    'node_id': 'MDU6TGFiZWwxMjgwOTg4NDI3',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Typing',\n",
       "    'name': 'Typing',\n",
       "    'color': 'ea91a4',\n",
       "    'default': False,\n",
       "    'description': 'mypy type annotations'}],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': None,\n",
       "  'comments': 1,\n",
       "  'created_at': '2021-02-18T22:17:10Z',\n",
       "  'updated_at': '2021-02-19T08:51:02Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'CONTRIBUTOR',\n",
       "  'active_lock_reason': None,\n",
       "  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/39897',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/pull/39897',\n",
       "   'diff_url': 'https://github.com/pandas-dev/pandas/pull/39897.diff',\n",
       "   'patch_url': 'https://github.com/pandas-dev/pandas/pull/39897.patch'},\n",
       "  'body': 'Add types to `pandas/core/indexes/base.py`.\\r\\n',\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39896',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39896/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39896/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39896/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/39896',\n",
       "  'id': 811487979,\n",
       "  'node_id': 'MDU6SXNzdWU4MTE0ODc5Nzk=',\n",
       "  'number': 39896,\n",
       "  'title': 'BUG: Ignore_index on concat does not ignore index ',\n",
       "  'user': {'login': 'mvirag2000',\n",
       "   'id': 23381596,\n",
       "   'node_id': 'MDQ6VXNlcjIzMzgxNTk2',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/23381596?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/mvirag2000',\n",
       "   'html_url': 'https://github.com/mvirag2000',\n",
       "   'followers_url': 'https://api.github.com/users/mvirag2000/followers',\n",
       "   'following_url': 'https://api.github.com/users/mvirag2000/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/mvirag2000/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/mvirag2000/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/mvirag2000/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/mvirag2000/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/mvirag2000/repos',\n",
       "   'events_url': 'https://api.github.com/users/mvirag2000/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/mvirag2000/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [{'id': 76811,\n",
       "    'node_id': 'MDU6TGFiZWw3NjgxMQ==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',\n",
       "    'name': 'Bug',\n",
       "    'color': 'e10c02',\n",
       "    'default': False,\n",
       "    'description': None},\n",
       "   {'id': 307649777,\n",
       "    'node_id': 'MDU6TGFiZWwzMDc2NDk3Nzc=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Info',\n",
       "    'name': 'Needs Info',\n",
       "    'color': '207de5',\n",
       "    'default': False,\n",
       "    'description': 'Clarification about behavior needed to assess issue'},\n",
       "   {'id': 13098779,\n",
       "    'node_id': 'MDU6TGFiZWwxMzA5ODc3OQ==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Reshaping',\n",
       "    'name': 'Reshaping',\n",
       "    'color': '02d7e1',\n",
       "    'default': False,\n",
       "    'description': 'Concat, Merge/Join, Stack/Unstack'}],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': None,\n",
       "  'comments': 1,\n",
       "  'created_at': '2021-02-18T21:40:02Z',\n",
       "  'updated_at': '2021-02-19T20:43:37Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'NONE',\n",
       "  'active_lock_reason': None,\n",
       "  'body': 'I have this line of code which works fine in pandas 1.1.5 but not in 1.2.2:\\r\\n\\r\\n`vintable = pd.concat([vintable, data], join=\\'inner\\', ignore_index=True)`\\r\\n\\r\\nI expect this to concatenate the rows, inner-join the columns, and then reindex - which it used to do in December.  But now I get this error: \"Reindexing only valid with uniquely valued Index objects.\"  As I read the docs, it should not be looking at the index at all.  So, I am fine sticking with 1.1.5 but I think is a bug ... TIA \\r\\n\\r\\n\\r\\n\\r\\n',\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39895',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39895/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39895/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39895/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/39895',\n",
       "  'id': 811458886,\n",
       "  'node_id': 'MDU6SXNzdWU4MTE0NTg4ODY=',\n",
       "  'number': 39895,\n",
       "  'title': \"BUG: groupby dropna=False doesn't work for multi index columns\",\n",
       "  'user': {'login': 'deepers',\n",
       "   'id': 17277714,\n",
       "   'node_id': 'MDQ6VXNlcjE3Mjc3NzE0',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/17277714?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/deepers',\n",
       "   'html_url': 'https://github.com/deepers',\n",
       "   'followers_url': 'https://api.github.com/users/deepers/followers',\n",
       "   'following_url': 'https://api.github.com/users/deepers/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/deepers/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/deepers/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/deepers/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/deepers/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/deepers/repos',\n",
       "   'events_url': 'https://api.github.com/users/deepers/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/deepers/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [{'id': 76811,\n",
       "    'node_id': 'MDU6TGFiZWw3NjgxMQ==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',\n",
       "    'name': 'Bug',\n",
       "    'color': 'e10c02',\n",
       "    'default': False,\n",
       "    'description': None},\n",
       "   {'id': 1954720290,\n",
       "    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',\n",
       "    'name': 'Needs Triage',\n",
       "    'color': '0052cc',\n",
       "    'default': False,\n",
       "    'description': 'Issue that has not been reviewed by a pandas team member'}],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': None,\n",
       "  'comments': 0,\n",
       "  'created_at': '2021-02-18T21:09:13Z',\n",
       "  'updated_at': '2021-02-18T21:09:13Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'NONE',\n",
       "  'active_lock_reason': None,\n",
       "  'body': '- [x] I have checked that this issue has not already been reported.\\r\\n\\r\\n- [x] I have confirmed this bug exists on the latest version of pandas.\\r\\n\\r\\n- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.\\r\\n\\r\\n---\\r\\n#### Code Sample\\r\\n\\r\\n```python\\r\\nIn [1]: df = pd.DataFrame(dict(a=[nan], b=[0], c=[1]))\\r\\nIn [2]: df\\r\\n    a  b  c\\r\\n0 NaN  0  1\\r\\n\\r\\n# groupby drops groups with null by default\\r\\nIn [3]: df.groupby([\\'a\\', \\'b\\']).first()\\r\\nEmpty DataFrame\\r\\nColumns: [c]\\r\\nIndex: []\\r\\n\\r\\n# pass dropna=False to keep groups with nulls\\r\\nIn [4]: df.groupby([\\'a\\', \\'b\\'], dropna=False).first()\\r\\n       c\\r\\na   b   \\r\\nNaN 0  1\\r\\n\\r\\n# This doesn\\'t work if the groups are in a multi index.\\r\\nIn [5]: df.set_index([\\'a\\', \\'b\\']).groupby([\\'a\\', \\'b\\'], dropna=False).first()\\r\\nEmpty DataFrame\\r\\nColumns: [c]\\r\\nIndex: []\\r\\n```\\r\\n\\r\\n#### Problem description\\r\\nIt seems like setting `dropna=False` in `groupby` doesn\\'t work when the group columns are part of a multi index. I\\'m not sure if this is intentional, but it is certainly confusing.\\r\\n\\r\\n#### Expected Output\\r\\nI would expect the output of [5] above to match that of [4].\\r\\n\\r\\n#### Output of ``pd.show_versions()``\\r\\n<details>\\r\\n\\r\\n```json\\r\\n{\\r\\n  \"system\": {\\r\\n    \"commit\": \"7d32926db8f7541c356066dcadabf854487738de\",\\r\\n    \"python\": \"3.8.5.final.0\",\\r\\n    \"python-bits\": 64,\\r\\n    \"OS\": \"Linux\",\\r\\n    \"OS-release\": \"5.4.0-1035-aws\",\\r\\n    \"Version\": \"#37-Ubuntu SMP Wed Jan 6 21:01:57 UTC 2021\",\\r\\n    \"machine\": \"x86_64\",\\r\\n    \"processor\": \"x86_64\",\\r\\n    \"byteorder\": \"little\",\\r\\n    \"LC_ALL\": \"C.UTF-8\",\\r\\n    \"LANG\": \"C.UTF-8\",\\r\\n    \"LOCALE\": {\\r\\n      \"language-code\": \"en_US\",\\r\\n      \"encoding\": \"UTF-8\"\\r\\n    }\\r\\n  },\\r\\n  \"dependencies\": {\\r\\n    \"pandas\": \"1.2.2\",\\r\\n    \"numpy\": \"1.20.1\",\\r\\n    \"pytz\": \"2021.1\",\\r\\n    \"dateutil\": \"2.8.1\",\\r\\n    \"pip\": \"20.3.3\",\\r\\n    \"setuptools\": \"51.3.3\",\\r\\n    \"Cython\": null,\\r\\n    \"pytest\": null,\\r\\n    \"hypothesis\": null,\\r\\n    \"sphinx\": null,\\r\\n    \"blosc\": null,\\r\\n    \"feather\": null,\\r\\n    \"xlsxwriter\": null,\\r\\n    \"lxml.etree\": null,\\r\\n    \"html5lib\": null,\\r\\n    \"pymysql\": null,\\r\\n    \"psycopg2\": null,\\r\\n    \"jinja2\": null,\\r\\n    \"IPython\": \"7.20.0\",\\r\\n    \"pandas_datareader\": null,\\r\\n    \"bs4\": \"4.9.3\",\\r\\n    \"bottleneck\": null,\\r\\n    \"fsspec\": null,\\r\\n    \"fastparquet\": \"0.5.0\",\\r\\n    \"gcsfs\": null,\\r\\n    \"matplotlib\": null,\\r\\n    \"numexpr\": null,\\r\\n    \"odfpy\": null,\\r\\n    \"openpyxl\": null,\\r\\n    \"pandas_gbq\": null,\\r\\n    \"pyarrow\": \"3.0.0\",\\r\\n    \"pyxlsb\": null,\\r\\n    \"s3fs\": null,\\r\\n    \"scipy\": null,\\r\\n    \"sqlalchemy\": null,\\r\\n    \"tables\": null,\\r\\n    \"tabulate\": null,\\r\\n    \"xarray\": null,\\r\\n    \"xlrd\": null,\\r\\n    \"xlwt\": null,\\r\\n    \"numba\": \"0.52.0\"\\r\\n  }\\r\\n}\\r\\n```\\r\\n\\r\\n</details>',\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39890',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39890/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39890/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39890/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/pull/39890',\n",
       "  'id': 811291703,\n",
       "  'node_id': 'MDExOlB1bGxSZXF1ZXN0NTc1ODQ0MTE4',\n",
       "  'number': 39890,\n",
       "  'title': 'Breaking change to offsets.pyx - quarter offset classes',\n",
       "  'user': {'login': 'Pawel-Kranzberg',\n",
       "   'id': 7954786,\n",
       "   'node_id': 'MDQ6VXNlcjc5NTQ3ODY=',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/7954786?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/Pawel-Kranzberg',\n",
       "   'html_url': 'https://github.com/Pawel-Kranzberg',\n",
       "   'followers_url': 'https://api.github.com/users/Pawel-Kranzberg/followers',\n",
       "   'following_url': 'https://api.github.com/users/Pawel-Kranzberg/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/Pawel-Kranzberg/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/Pawel-Kranzberg/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/Pawel-Kranzberg/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/Pawel-Kranzberg/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/Pawel-Kranzberg/repos',\n",
       "   'events_url': 'https://api.github.com/users/Pawel-Kranzberg/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/Pawel-Kranzberg/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [{'id': 53181044,\n",
       "    'node_id': 'MDU6TGFiZWw1MzE4MTA0NA==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Frequency',\n",
       "    'name': 'Frequency',\n",
       "    'color': '0052cc',\n",
       "    'default': False,\n",
       "    'description': 'DateOffsets'}],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': None,\n",
       "  'comments': 5,\n",
       "  'created_at': '2021-02-18T17:07:42Z',\n",
       "  'updated_at': '2021-02-19T07:18:39Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'NONE',\n",
       "  'active_lock_reason': None,\n",
       "  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/39890',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/pull/39890',\n",
       "   'diff_url': 'https://github.com/pandas-dev/pandas/pull/39890.diff',\n",
       "   'patch_url': 'https://github.com/pandas-dev/pandas/pull/39890.patch'},\n",
       "  'body': 'Set default months for `BQuarterEnd`, `BQuarterBegin`, `QuarterEnd`, `QuarterBegin` classes in order.\\r\\nAddresses #8435\\r\\n\\r\\n- [ ] closes #8435\\r\\n- [ ] tests added / passed\\r\\n- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them\\r\\n- [ ] whatsnew entry\\r\\n',\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39889',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39889/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39889/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39889/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/pull/39889',\n",
       "  'id': 811277675,\n",
       "  'node_id': 'MDExOlB1bGxSZXF1ZXN0NTc1ODMyNDAw',\n",
       "  'number': 39889,\n",
       "  'title': 'BUG: Bg gradient map text color fix',\n",
       "  'user': {'login': 'attack68',\n",
       "   'id': 24256554,\n",
       "   'node_id': 'MDQ6VXNlcjI0MjU2NTU0',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/24256554?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/attack68',\n",
       "   'html_url': 'https://github.com/attack68',\n",
       "   'followers_url': 'https://api.github.com/users/attack68/followers',\n",
       "   'following_url': 'https://api.github.com/users/attack68/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/attack68/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/attack68/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/attack68/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/attack68/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/attack68/repos',\n",
       "   'events_url': 'https://api.github.com/users/attack68/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/attack68/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [{'id': 76811,\n",
       "    'node_id': 'MDU6TGFiZWw3NjgxMQ==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',\n",
       "    'name': 'Bug',\n",
       "    'color': 'e10c02',\n",
       "    'default': False,\n",
       "    'description': None},\n",
       "   {'id': 1728592794,\n",
       "    'node_id': 'MDU6TGFiZWwxNzI4NTkyNzk0',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Styler',\n",
       "    'name': 'Styler',\n",
       "    'color': '006b75',\n",
       "    'default': False,\n",
       "    'description': 'conditional formatting using DataFrame.style'}],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': {'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/80',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/milestone/80',\n",
       "   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/80/labels',\n",
       "   'id': 6095818,\n",
       "   'node_id': 'MDk6TWlsZXN0b25lNjA5NTgxOA==',\n",
       "   'number': 80,\n",
       "   'title': '1.3',\n",
       "   'description': '',\n",
       "   'creator': {'login': 'jreback',\n",
       "    'id': 953992,\n",
       "    'node_id': 'MDQ6VXNlcjk1Mzk5Mg==',\n",
       "    'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4',\n",
       "    'gravatar_id': '',\n",
       "    'url': 'https://api.github.com/users/jreback',\n",
       "    'html_url': 'https://github.com/jreback',\n",
       "    'followers_url': 'https://api.github.com/users/jreback/followers',\n",
       "    'following_url': 'https://api.github.com/users/jreback/following{/other_user}',\n",
       "    'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}',\n",
       "    'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}',\n",
       "    'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions',\n",
       "    'organizations_url': 'https://api.github.com/users/jreback/orgs',\n",
       "    'repos_url': 'https://api.github.com/users/jreback/repos',\n",
       "    'events_url': 'https://api.github.com/users/jreback/events{/privacy}',\n",
       "    'received_events_url': 'https://api.github.com/users/jreback/received_events',\n",
       "    'type': 'User',\n",
       "    'site_admin': False},\n",
       "   'open_issues': 111,\n",
       "   'closed_issues': 834,\n",
       "   'state': 'open',\n",
       "   'created_at': '2020-11-11T19:05:43Z',\n",
       "   'updated_at': '2021-02-19T18:32:12Z',\n",
       "   'due_on': '2021-05-31T07:00:00Z',\n",
       "   'closed_at': None},\n",
       "  'comments': 0,\n",
       "  'created_at': '2021-02-18T16:50:29Z',\n",
       "  'updated_at': '2021-02-19T06:17:40Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'CONTRIBUTOR',\n",
       "  'active_lock_reason': None,\n",
       "  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/39889',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/pull/39889',\n",
       "   'diff_url': 'https://github.com/pandas-dev/pandas/pull/39889.diff',\n",
       "   'patch_url': 'https://github.com/pandas-dev/pandas/pull/39889.patch'},\n",
       "  'body': '- [x] closes #39888 \\r\\n',\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39888',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39888/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39888/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39888/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/39888',\n",
       "  'id': 811274798,\n",
       "  'node_id': 'MDU6SXNzdWU4MTEyNzQ3OTg=',\n",
       "  'number': 39888,\n",
       "  'title': 'BUG: Relative luminance calc in Styler is wrong (and out of date) ',\n",
       "  'user': {'login': 'attack68',\n",
       "   'id': 24256554,\n",
       "   'node_id': 'MDQ6VXNlcjI0MjU2NTU0',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/24256554?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/attack68',\n",
       "   'html_url': 'https://github.com/attack68',\n",
       "   'followers_url': 'https://api.github.com/users/attack68/followers',\n",
       "   'following_url': 'https://api.github.com/users/attack68/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/attack68/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/attack68/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/attack68/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/attack68/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/attack68/repos',\n",
       "   'events_url': 'https://api.github.com/users/attack68/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/attack68/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [{'id': 76811,\n",
       "    'node_id': 'MDU6TGFiZWw3NjgxMQ==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',\n",
       "    'name': 'Bug',\n",
       "    'color': 'e10c02',\n",
       "    'default': False,\n",
       "    'description': None},\n",
       "   {'id': 1728592794,\n",
       "    'node_id': 'MDU6TGFiZWwxNzI4NTkyNzk0',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Styler',\n",
       "    'name': 'Styler',\n",
       "    'color': '006b75',\n",
       "    'default': False,\n",
       "    'description': 'conditional formatting using DataFrame.style'},\n",
       "   {'id': 2413328,\n",
       "    'node_id': 'MDU6TGFiZWwyNDEzMzI4',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Visualization',\n",
       "    'name': 'Visualization',\n",
       "    'color': '8AE234',\n",
       "    'default': False,\n",
       "    'description': None}],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': {'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/80',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/milestone/80',\n",
       "   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/80/labels',\n",
       "   'id': 6095818,\n",
       "   'node_id': 'MDk6TWlsZXN0b25lNjA5NTgxOA==',\n",
       "   'number': 80,\n",
       "   'title': '1.3',\n",
       "   'description': '',\n",
       "   'creator': {'login': 'jreback',\n",
       "    'id': 953992,\n",
       "    'node_id': 'MDQ6VXNlcjk1Mzk5Mg==',\n",
       "    'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4',\n",
       "    'gravatar_id': '',\n",
       "    'url': 'https://api.github.com/users/jreback',\n",
       "    'html_url': 'https://github.com/jreback',\n",
       "    'followers_url': 'https://api.github.com/users/jreback/followers',\n",
       "    'following_url': 'https://api.github.com/users/jreback/following{/other_user}',\n",
       "    'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}',\n",
       "    'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}',\n",
       "    'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions',\n",
       "    'organizations_url': 'https://api.github.com/users/jreback/orgs',\n",
       "    'repos_url': 'https://api.github.com/users/jreback/repos',\n",
       "    'events_url': 'https://api.github.com/users/jreback/events{/privacy}',\n",
       "    'received_events_url': 'https://api.github.com/users/jreback/received_events',\n",
       "    'type': 'User',\n",
       "    'site_admin': False},\n",
       "   'open_issues': 111,\n",
       "   'closed_issues': 834,\n",
       "   'state': 'open',\n",
       "   'created_at': '2020-11-11T19:05:43Z',\n",
       "   'updated_at': '2021-02-19T18:32:12Z',\n",
       "   'due_on': '2021-05-31T07:00:00Z',\n",
       "   'closed_at': None},\n",
       "  'comments': 0,\n",
       "  'created_at': '2021-02-18T16:46:55Z',\n",
       "  'updated_at': '2021-02-19T01:07:16Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'CONTRIBUTOR',\n",
       "  'active_lock_reason': None,\n",
       "  'body': 'The relative luminance calculation is described here: https://www.w3.org/WAI/GL/wiki/Relative_luminance. RL is used by `Styler.background_gradient()` to determine text-color against background but the calculation is wrongly coded.\\r\\n\\r\\nIn addition a new errata posted suggests that a scalar should be changed (albeit this has minimal impact). The greatest change is had through the re-engineered calculation. See below for before and after.\\r\\n\\r\\n![Screen Shot 2021-02-18 at 17 41 17](https://user-images.githubusercontent.com/24256554/108390583-1bb83680-7211-11eb-90b1-cffc4daa4c2d.png)\\r\\n',\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39887',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39887/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39887/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39887/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/pull/39887',\n",
       "  'id': 811266195,\n",
       "  'node_id': 'MDExOlB1bGxSZXF1ZXN0NTc1ODIyNzA2',\n",
       "  'number': 39887,\n",
       "  'title': '[BUG] Breaking change to offsets.pyx - MonthOffset',\n",
       "  'user': {'login': 'Pawel-Kranzberg',\n",
       "   'id': 7954786,\n",
       "   'node_id': 'MDQ6VXNlcjc5NTQ3ODY=',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/7954786?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/Pawel-Kranzberg',\n",
       "   'html_url': 'https://github.com/Pawel-Kranzberg',\n",
       "   'followers_url': 'https://api.github.com/users/Pawel-Kranzberg/followers',\n",
       "   'following_url': 'https://api.github.com/users/Pawel-Kranzberg/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/Pawel-Kranzberg/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/Pawel-Kranzberg/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/Pawel-Kranzberg/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/Pawel-Kranzberg/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/Pawel-Kranzberg/repos',\n",
       "   'events_url': 'https://api.github.com/users/Pawel-Kranzberg/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/Pawel-Kranzberg/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [{'id': 53181044,\n",
       "    'node_id': 'MDU6TGFiZWw1MzE4MTA0NA==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Frequency',\n",
       "    'name': 'Frequency',\n",
       "    'color': '0052cc',\n",
       "    'default': False,\n",
       "    'description': 'DateOffsets'}],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': None,\n",
       "  'comments': 1,\n",
       "  'created_at': '2021-02-18T16:37:04Z',\n",
       "  'updated_at': '2021-02-19T02:17:02Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'NONE',\n",
       "  'active_lock_reason': None,\n",
       "  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/39887',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/pull/39887',\n",
       "   'diff_url': 'https://github.com/pandas-dev/pandas/pull/39887.diff',\n",
       "   'patch_url': 'https://github.com/pandas-dev/pandas/pull/39887.patch'},\n",
       "  'body': 'Add ability to use `MonthBegin`, `BusinessMonthBegin` and `BusinessMonthEnd` as periods, e.g., by using their offset aliases as `freq` in `date_range`.\\r\\nIt would address #38914 and #38859.\\r\\n\\r\\n- [ ] closes #38914 #38859\\r\\n- [ ] tests added / passed\\r\\n- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them\\r\\n- [ ] whatsnew entry\\r\\n',\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39886',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39886/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39886/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39886/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/pull/39886',\n",
       "  'id': 811200879,\n",
       "  'node_id': 'MDExOlB1bGxSZXF1ZXN0NTc1NzY3NDc0',\n",
       "  'number': 39886,\n",
       "  'title': 'correction to get time interpolation correct',\n",
       "  'user': {'login': 'oricou',\n",
       "   'id': 7228177,\n",
       "   'node_id': 'MDQ6VXNlcjcyMjgxNzc=',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/7228177?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/oricou',\n",
       "   'html_url': 'https://github.com/oricou',\n",
       "   'followers_url': 'https://api.github.com/users/oricou/followers',\n",
       "   'following_url': 'https://api.github.com/users/oricou/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/oricou/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/oricou/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/oricou/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/oricou/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/oricou/repos',\n",
       "   'events_url': 'https://api.github.com/users/oricou/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/oricou/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [{'id': 2822342,\n",
       "    'node_id': 'MDU6TGFiZWwyODIyMzQy',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Missing-data',\n",
       "    'name': 'Missing-data',\n",
       "    'color': 'd7e102',\n",
       "    'default': False,\n",
       "    'description': None}],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': None,\n",
       "  'comments': 1,\n",
       "  'created_at': '2021-02-18T15:24:43Z',\n",
       "  'updated_at': '2021-02-19T12:03:39Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'NONE',\n",
       "  'active_lock_reason': None,\n",
       "  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/39886',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/pull/39886',\n",
       "   'diff_url': 'https://github.com/pandas-dev/pandas/pull/39886.diff',\n",
       "   'patch_url': 'https://github.com/pandas-dev/pandas/pull/39886.patch'},\n",
       "  'body': \"- [ ] closes #21351\\r\\n- [ ] One test does not pass and I don't know why\\r\\n\",\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39885',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39885/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39885/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39885/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/pull/39885',\n",
       "  'id': 811156448,\n",
       "  'node_id': 'MDExOlB1bGxSZXF1ZXN0NTc1NzMwMTEy',\n",
       "  'number': 39885,\n",
       "  'title': '[ArrayManager] GroupBy cython aggregations (no fallback)',\n",
       "  'user': {'login': 'jorisvandenbossche',\n",
       "   'id': 1020496,\n",
       "   'node_id': 'MDQ6VXNlcjEwMjA0OTY=',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/1020496?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/jorisvandenbossche',\n",
       "   'html_url': 'https://github.com/jorisvandenbossche',\n",
       "   'followers_url': 'https://api.github.com/users/jorisvandenbossche/followers',\n",
       "   'following_url': 'https://api.github.com/users/jorisvandenbossche/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/jorisvandenbossche/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/jorisvandenbossche/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/jorisvandenbossche/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/jorisvandenbossche/repos',\n",
       "   'events_url': 'https://api.github.com/users/jorisvandenbossche/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/jorisvandenbossche/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [{'id': 233160,\n",
       "    'node_id': 'MDU6TGFiZWwyMzMxNjA=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Groupby',\n",
       "    'name': 'Groupby',\n",
       "    'color': '729FCF',\n",
       "    'default': False,\n",
       "    'description': None},\n",
       "   {'id': 49094459,\n",
       "    'node_id': 'MDU6TGFiZWw0OTA5NDQ1OQ==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Internals',\n",
       "    'name': 'Internals',\n",
       "    'color': 'fbca04',\n",
       "    'default': False,\n",
       "    'description': 'Related to non-user accessible pandas implementation'}],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': {'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/80',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/milestone/80',\n",
       "   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/80/labels',\n",
       "   'id': 6095818,\n",
       "   'node_id': 'MDk6TWlsZXN0b25lNjA5NTgxOA==',\n",
       "   'number': 80,\n",
       "   'title': '1.3',\n",
       "   'description': '',\n",
       "   'creator': {'login': 'jreback',\n",
       "    'id': 953992,\n",
       "    'node_id': 'MDQ6VXNlcjk1Mzk5Mg==',\n",
       "    'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4',\n",
       "    'gravatar_id': '',\n",
       "    'url': 'https://api.github.com/users/jreback',\n",
       "    'html_url': 'https://github.com/jreback',\n",
       "    'followers_url': 'https://api.github.com/users/jreback/followers',\n",
       "    'following_url': 'https://api.github.com/users/jreback/following{/other_user}',\n",
       "    'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}',\n",
       "    'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}',\n",
       "    'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions',\n",
       "    'organizations_url': 'https://api.github.com/users/jreback/orgs',\n",
       "    'repos_url': 'https://api.github.com/users/jreback/repos',\n",
       "    'events_url': 'https://api.github.com/users/jreback/events{/privacy}',\n",
       "    'received_events_url': 'https://api.github.com/users/jreback/received_events',\n",
       "    'type': 'User',\n",
       "    'site_admin': False},\n",
       "   'open_issues': 111,\n",
       "   'closed_issues': 834,\n",
       "   'state': 'open',\n",
       "   'created_at': '2020-11-11T19:05:43Z',\n",
       "   'updated_at': '2021-02-19T18:32:12Z',\n",
       "   'due_on': '2021-05-31T07:00:00Z',\n",
       "   'closed_at': None},\n",
       "  'comments': 0,\n",
       "  'created_at': '2021-02-18T14:35:58Z',\n",
       "  'updated_at': '2021-02-19T01:25:36Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'MEMBER',\n",
       "  'active_lock_reason': None,\n",
       "  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/39885',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/pull/39885',\n",
       "   'diff_url': 'https://github.com/pandas-dev/pandas/pull/39885.diff',\n",
       "   'patch_url': 'https://github.com/pandas-dev/pandas/pull/39885.patch'},\n",
       "  'body': 'xref https://github.com/pandas-dev/pandas/issues/39146/\\r\\n\\r\\nThis implements one aspect of groupby: basic cython-based aggregations (so not yet general apply, python fallback, or other methods, etc, only the basic aggregations that take the `_cython_agg_general` path).\\r\\n\\r\\nSimilarly to how we currently have a `_cython_agg_blocks`, this PR adds an equivalent `_cython_agg_arrays` which calls the cython operation on each column instead of each block.',\n",
       "  'performed_via_github_app': None},\n",
       " {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39882',\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39882/labels{/name}',\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39882/comments',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39882/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/39882',\n",
       "  'id': 810915761,\n",
       "  'node_id': 'MDU6SXNzdWU4MTA5MTU3NjE=',\n",
       "  'number': 39882,\n",
       "  'title': 'BUG: InvalidIndexError: Reindexing only valid with uniquely valued Index objects on to_datetime',\n",
       "  'user': {'login': 'jafournier',\n",
       "   'id': 16292862,\n",
       "   'node_id': 'MDQ6VXNlcjE2MjkyODYy',\n",
       "   'avatar_url': 'https://avatars.githubusercontent.com/u/16292862?v=4',\n",
       "   'gravatar_id': '',\n",
       "   'url': 'https://api.github.com/users/jafournier',\n",
       "   'html_url': 'https://github.com/jafournier',\n",
       "   'followers_url': 'https://api.github.com/users/jafournier/followers',\n",
       "   'following_url': 'https://api.github.com/users/jafournier/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/jafournier/gists{/gist_id}',\n",
       "   'starred_url': 'https://api.github.com/users/jafournier/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/jafournier/subscriptions',\n",
       "   'organizations_url': 'https://api.github.com/users/jafournier/orgs',\n",
       "   'repos_url': 'https://api.github.com/users/jafournier/repos',\n",
       "   'events_url': 'https://api.github.com/users/jafournier/events{/privacy}',\n",
       "   'received_events_url': 'https://api.github.com/users/jafournier/received_events',\n",
       "   'type': 'User',\n",
       "   'site_admin': False},\n",
       "  'labels': [{'id': 76811,\n",
       "    'node_id': 'MDU6TGFiZWw3NjgxMQ==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',\n",
       "    'name': 'Bug',\n",
       "    'color': 'e10c02',\n",
       "    'default': False,\n",
       "    'description': None},\n",
       "   {'id': 1954720290,\n",
       "    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',\n",
       "    'name': 'Needs Triage',\n",
       "    'color': '0052cc',\n",
       "    'default': False,\n",
       "    'description': 'Issue that has not been reviewed by a pandas team member'}],\n",
       "  'state': 'open',\n",
       "  'locked': False,\n",
       "  'assignee': None,\n",
       "  'assignees': [],\n",
       "  'milestone': None,\n",
       "  'comments': 0,\n",
       "  'created_at': '2021-02-18T09:21:54Z',\n",
       "  'updated_at': '2021-02-18T09:35:51Z',\n",
       "  'closed_at': None,\n",
       "  'author_association': 'NONE',\n",
       "  'active_lock_reason': None,\n",
       "  'body': '#### Problem description\\r\\nI am expriencing a weird bug while trying to convert a list to datetime.\\r\\nHere is a bug repro:\\r\\n```python\\r\\nimport pandas as pd\\r\\ns = pd.Series([None, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.Timestamp(\\'2016-06-07 20:07:42\\'), pd.NaT, pd.Timestamp(\\'2016-05-04 20:09:22\\'), pd.Timestamp(\\'2016-04-12 20:07:40\\'), pd.Timestamp(\\'2016-03-30 20:10:39\\'), pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.Timestamp(\\'2015-12-18 20:14:06\\'), pd.Timestamp(\\'2015-12-15 20:07:59\\'), pd.Timestamp(\\'2015-11-17 20:09:31\\'), pd.Timestamp(\\'2015-11-05 20:10:41\\'), pd.Timestamp(\\'2015-10-29 20:12:12\\'), pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.Timestamp(\\'2015-07-20 20:10:23\\'), pd.Timestamp(\\'2015-06-16 20:07:24\\'), pd.Timestamp(\\'2015-05-28 20:09:39\\'), pd.NaT, pd.NaT, pd.Timestamp(\\'2015-04-15 20:12:54\\'), pd.NaT, pd.NaT, pd.NaT, pd.Timestamp(\\'2015-02-20 20:12:07\\'), pd.Timestamp(\\'2014-12-29 20:04:30\\'), pd.Timestamp(\\'2014-12-15 20:09:24\\'), pd.NaT, pd.NaT, pd.Timestamp(\\'2014-11-17 20:03:56\\'), pd.NaT, pd.Timestamp(\\'2014-10-14 20:04:47\\'), pd.NaT, pd.NaT, pd.NaT, pd.NaT, pd.Timestamp(\\'2014-08-21 20:06:15\\'), pd.NaT, pd.Timestamp(\\'2012-07-26 00:10:29\\')], dtype=\"object\")\\r\\npd.to_datetime(s, errors=\"coerce\")\\r\\n```\\r\\nWhat I got is :\\r\\n```\\r\\nInvalidIndexError: Reindexing only valid with uniquely valued Index objects\\r\\n```\\r\\nTesting on other example, the behavior is working as expected:\\r\\n\\r\\n```python\\r\\nimport pandas as pd\\r\\ns = pd.Series([None, pd.NaT, pd.Timestamp(\\'2014-11-17 20:03:56\\')], dtype=\"object\")\\r\\npd.to_datetime(s, errors=\"coerce\")\\r\\n```\\r\\ngives me \\r\\n```\\r\\n0                   NaT\\r\\n1                   NaT\\r\\n2   2014-11-17 20:03:56\\r\\ndtype: datetime64[ns]\\r\\n```\\r\\n#### Output of ``pd.show_versions()``\\r\\n<details>\\r\\n\\r\\nINSTALLED VERSIONS\\r\\n------------------\\r\\ncommit           : 7d32926db8f7541c356066dcadabf854487738de\\r\\npython           : 3.7.4.final.0\\r\\npython-bits      : 64\\r\\nOS               : Darwin\\r\\nOS-release       : 19.6.0\\r\\nVersion          : Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64\\r\\nmachine          : x86_64\\r\\nprocessor        : i386\\r\\nbyteorder        : little\\r\\nLC_ALL           : en_US.UTF-8\\r\\nLANG             : en_US.UTF-8\\r\\nLOCALE           : en_US.UTF-8\\r\\n\\r\\npandas           : 1.2.2\\r\\nnumpy            : 1.19.4\\r\\npytz             : 2020.4\\r\\ndateutil         : 2.8.1\\r\\npip              : 20.2.4\\r\\nsetuptools       : 40.8.0\\r\\nCython           : None\\r\\npytest           : None\\r\\nhypothesis       : None\\r\\nsphinx           : None\\r\\nblosc            : None\\r\\nfeather          : None\\r\\nxlsxwriter       : None\\r\\nlxml.etree       : None\\r\\nhtml5lib         : 1.1\\r\\npymysql          : None\\r\\npsycopg2         : None\\r\\njinja2           : None\\r\\nIPython          : 7.19.0\\r\\npandas_datareader: None\\r\\nbs4              : None\\r\\nbottleneck       : None\\r\\nfsspec           : 0.8.5\\r\\nfastparquet      : None\\r\\ngcsfs            : None\\r\\nmatplotlib       : None\\r\\nnumexpr          : None\\r\\nodfpy            : None\\r\\nopenpyxl         : None\\r\\npandas_gbq       : None\\r\\npyarrow          : 2.0.0\\r\\npyxlsb           : None\\r\\ns3fs             : 0.2.2\\r\\nscipy            : 1.5.4\\r\\nsqlalchemy       : None\\r\\ntables           : None\\r\\ntabulate         : None\\r\\nxarray           : None\\r\\nxlrd             : 2.0.1\\r\\nxlwt             : None\\r\\nnumba            : None\\r\\n\\r\\n</details>\\r\\n\\r\\nInfo while scrolling a bit with pdb:\\r\\n```\\r\\n> /Users/jfournier/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pandas/core/tools/datetimes.py(803)to_datetime()\\r\\n    801         cache_array = _maybe_cache(arg, format, cache, convert_listlike)\\r\\n    802         if not cache_array.empty:\\r\\n--> 803             result = arg.map(cache_array)\\r\\n    804         else:\\r\\n    805             values = convert_listlike(arg._values, format)\\r\\n\\r\\nipdb> cache_array\\r\\nNaT                                   NaT\\r\\nNaT                                   NaT\\r\\n2016-06-07 20:07:42   2016-06-07 20:07:42\\r\\n2016-05-04 20:09:22   2016-05-04 20:09:22\\r\\n2016-04-12 20:07:40   2016-04-12 20:07:40\\r\\n2016-03-30 20:10:39   2016-03-30 20:10:39\\r\\n2015-12-18 20:14:06   2015-12-18 20:14:06\\r\\n2015-12-15 20:07:59   2015-12-15 20:07:59\\r\\n2015-11-17 20:09:31   2015-11-17 20:09:31\\r\\n2015-11-05 20:10:41   2015-11-05 20:10:41\\r\\n2015-10-29 20:12:12   2015-10-29 20:12:12\\r\\n2015-07-20 20:10:23   2015-07-20 20:10:23\\r\\n2015-06-16 20:07:24   2015-06-16 20:07:24\\r\\n2015-05-28 20:09:39   2015-05-28 20:09:39\\r\\n2015-04-15 20:12:54   2015-04-15 20:12:54\\r\\n2015-02-20 20:12:07   2015-02-20 20:12:07\\r\\n2014-12-29 20:04:30   2014-12-29 20:04:30\\r\\n2014-12-15 20:09:24   2014-12-15 20:09:24\\r\\n2014-11-17 20:03:56   2014-11-17 20:03:56\\r\\n2014-10-14 20:04:47   2014-10-14 20:04:47\\r\\n2014-08-21 20:06:15   2014-08-21 20:06:15\\r\\n2012-07-26 00:10:29   2012-07-26 00:10:29\\r\\ndtype: datetime64[ns]\\r\\n```\\r\\nit seems that there is a deduplication which distinguishes `None` from `NaT`, then `None` got converted  to `NaT`, and ultimately the `self.is_unique` check fails as `NaT` is present twice',\n",
       "  'performed_via_github_app': None}]"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "u"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "dict"
      ]
     },
     "execution_count": 26,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "type(u[0])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
